### ISSUE TITLE
error with GMCM

### ISSUE THREAD

**Issue by heyitsheather1784** [daleao/modular-overhaul#103]
Hi

I am having an issue were the menus of this mod don't load properly - see the image. 

It occurs with only GMCM + SPACECORE + MARGO in mods but I included the log for my full mod list as well 

Smapi log https://smapi.io/log/05a1c99f6d1042aeb5ad168745e60c8b
![image](https://github.com/daleao/modular-overhaul/assets/88039162/4339a5ab-21fd-4ea7-83d3-6eb705369b4d)

**Comment by daleao** [comment]
Either reinstall the entire mod, or just replace your i18n folder with [the one from this repo](https://github.com/daleao/modular-overhaul/tree/main/i18n).

**Comment by heyitsheather1784** [comment]
Thank you, that fixed it
