### ISSUE TITLE
Only normal quality mayonnaise

### ISSUE THREAD

**Issue by veselin-antonov** [daleao/modular-overhaul#104]
Today we started having this issue in our multiplayer game, where neither me, nor my girlfriend can get anything more than a normal quality mayonnaise. We both have all farming perks, on our way to prestige and we did not have this issue the last time we played. Here's my log: https://smapi.io/log/f87cebf1a9eb450ba5cf1c47017b7a25 where I did a quick test and the issue is still reproducible on my end.

**Comment by daleao** [comment]
What's your current farming level?

**Comment by veselin-antonov** [comment]
Level 12 if I recall correctly.

**Comment by justinianfruit** [comment]
I am having this issue as well with all artisan machines that accept input, only normal quality output: mayo machines, looms, kegs, preserve jars. Tappers and bee houses however are still using the machine age determination to produce at higher quality. 
I tried setting the mod options "Artisan goods always input quality" to true and adding all default machines to the list of artisan machines but to no effect.

**Comment by daleao** [comment]
Open your config and check if the machine names are correct under `ArtisanMachines`.
There is a bug in 4.1.2 with GMCM cropping the names of the machines, so they will not be recognized as Artisan machines.
If that is the case, resetting your config file will resolve the issue.

**Comment by justinianfruit** [comment]
@daleao Which config file should I be checking? I looked at the config for MARGO and the array for `ArtisanMachines` is empty, but I'm not sure if this is the correct config file you're referring to?

**Comment by Exaxxion** [comment]
The config file you want is `Mods/ModularOverhaul/config.json`.

Professions contains `ArtisanMachines` and `AnimalDerivedGoods` which are both arrays and I can confirm that in my file the machine and item names are truncated from having used GMCM to modify the config in-game.

Looking at the config class in the Professions module, I believe this is the intended default contents:
```
    "ArtisanMachines": [
      "Cheese Press",
        "Keg",
        "Loom",
        "Mayonnaise Machine",
        "Oil Maker",
        "Preserves Jar",
        "Alembic",
        "Artisanal Soda Maker",
        "Butter Churn",
        "Canning Machine",
        "Carbonator",
        "Cola Maker",
        "Cream Soda Maker",
        "DNA Synthesizer",
        "Dehydrator",
        "Drying Rack",
        "Espresso Machine",
        "Extruder",
        "Foreign Cask",
        "Glass Jar",
        "Grinder",
        "Ice Cream Machine",
        "Infuser",
        "Juicer",
        "Marble Soda Machine",
        "Meat Press",
        "Pepper Blender",
        "Shaved Ice Machine",
        "Smoker",
        "Soap Press",
        "Sorbet Machine",
        "Still",
        "Syrup Maker",
        "Vinegar Cask",
        "Wax Barrel",
        "Yogurt Jar",
    ],
    "AnimalDerivedGoods": [
      "Mayonnaise",
        "Duck Mayonnaise",
        "Void Mayonnaise",
        "Dinosaur Mayonnaise",
        "Cheese",
        "Goat Cheese",
        "Cloth",
        "Butter",
        "Goat Butter",
        "Yogurt",
        "Goat Yogurt",
        "Fruit Yogurt",
        "Kefir",
        "Kumis",
        "Lassi",
        "Avocado Mayonnaise",
        "Black Pepper Mayonnaise",
        "Garlic Mayonnaise",
        "Lucky Purple Mayonnaise",
        "Olive Oil Mayonnaise",
        "Thunder Mayonnaise",
        "Wasabi Mayonnaise",
        "Delight Mayonnaise",
        "Shiny Mayonnaise",
        "Slime Butter",
        "Slime Cheese",
        "Slime Mayonnaise",
    ],
```

**Comment by justinianfruit** [comment]
If so, I had the correct file and both arrays for `ArtisanMachines` and ` AnimalDerivedGoods` are entirely empty.

**Comment by Exaxxion** [comment]
I'd guess the game is overwriting the file contents on the day change. Maybe make the changes with the game closed so it will load with those values to begin with.

**Comment by justinianfruit** [comment]
That is what I had done, the machines and products were present when looking at the GMCM from the title screen after starting up SMAPI fresh from altering the config. But then when looking at the GMCM in game after loading into my save, it was empty again.

**Comment by Exaxxion** [comment]
Perhaps the bug that was mentioned earlier with GMCM presents by even opening GMCM to check on what it says the configs are in game. I looked over at [GMCM's parent repository](https://github.com/spacechase0/StardewValleyMods) but didn't see an issue describing this particular bug so I'd have to defer to daleao.

**Comment by justinianfruit** [comment]
In the meantime, I'm going a little nuclear with my mods. At one point, I was using vortex to manage mods but since I'm using quite a few mods not through Nexus I've since removed it. But it left a lot of artifacts related to vortex manager around in most of my mod folders. So I've deleted everything, including SMAPI, and will reinstall fresh to see if that fixes the conflict.

**Comment by daleao** [comment]
Please wait for the update.
