### ISSUE TITLE
Game crash when go to Mine with Prospector (Lv10)

### ISSUE THREAD

**Issue by bosssnkc** [daleao/modular-overhaul#108]
Hello i got game crash every time when i go to mine with Prospector (Lv10) Skills,
here some picture and my log.
https://smapi.io/log/deb642ffa146409797170685b925cce5
![image](https://github.com/daleao/modular-overhaul/assets/84249572/594dceb3-4dae-44fa-be2d-44da3cc1a3f4)

**Comment by daleao** [comment]
Update.
