### ISSUE TITLE
Mainly a question but possibly an issue

### ISSUE THREAD

**Issue by Noodleboiby** [daleao/modular-overhaul#11]
Does this mod shuffle the mine rewards? I don't seem to be getting the obsidian edge at the level 90 checkpoint but I'm not sure if that's intended or not

**Comment by daleao** [comment]
[Yes](https://github.com/daleao/modular-overhaul/tree/main/Modules/Combat#other-features).

**Comment by daleao** [comment]
To elaborate: Obsidian Edge is a mythical weapon with the Rebalance option. It can only be acquired as a rare drop from hard-mode shadow people.
