### ISSUE TITLE
Config of artisan machines, animal derived goods and dairy artisan machines disappearing

### ISSUE THREAD

**Issue by mars22253** [daleao/modular-overhaul#112]
When opening the MARGO config in GMCM mid game the entire config list for artisan machines, animal derived goods and dairy artisan machines disappear, as in the stuff like cheese press, kegs, cheese etc. Checking in the manual config shows that they are fully removed from the config and it isn't just GMCM glitching in game. I tried reinstalling MARGO and when editing the config file in the beginning popup from GMCM the list is there and editing is fine, only when reopening MARGO with GMCM mid game causes the list to disappear. The config list for stabbing weapons is fine however.
Here is my SMAPI log. https://smapi.io/log/d1deafe35ec042f7a1961d93a6b6aa00

**Comment by mars22253** [comment]
Forgot to mention this is after editing the artisan machines config list to add more machines.

**Comment by daleao** [comment]
Took a while to find the issue because it only happens in a specific edge case.
Turns out GMCM doesn't actually behave in the way I expected.
Will fix this soon. For now, as long as you don't hit Save on the initial menu page (the one with the links to each module) then it should be fine.
