### ISSUE TITLE
Disabling auto-selection option causes crash in parsing config json

### ISSUE THREAD

**Issue by Svcri** [daleao/modular-overhaul#113]
After changing configuration options through generic mod config menu, specifically unchecking auto-selection in CMBT and TOLS, the mod crashes on starting smapi.

Smapi log (with other mods disabled): https://smapi.io/log/f239d162c99a4793ab4ca3a36165111b

**Comment by daleao** [comment]
Just delete your config, or delete the `EnableAutoSelection` line in the Combat section.
