### ISSUE TITLE
crash after multiple prestige reset

### ISSUE THREAD

**Issue by tytanitex** [daleao/modular-overhaul#116]
I unlocked the sewer and reset my farming and fishing level 10s but i'm pretty sure it caused it to crash when i went to bed.
https://smapi.io/log/5f78ee8da6bd469b85b46d33546d8d7a

**Comment by daleao** [comment]
No errors in your log though.
Some people have reported this issue but I cannot reproduce it.
Just don't use the multiple prestige option.
