### ISSUE TITLE
Extra entry in TXS config?

### ISSUE THREAD

**Issue by taiwithers** [daleao/modular-overhaul#118]
![image](https://github.com/daleao/modular-overhaul/assets/59430904/d6a09f46-675c-4406-a1b6-b9fd3cb49112)
Not sure if "Example Object and Percentage" is intended to be there, apologies if it is.

**Comment by daleao** [comment]
The config file includes this as a template for those who wish to manually add non-vanilla deductibles.
It gets picked up by the auto-generated menu.
You can ignore it.
