### ISSUE TITLE
Taxes lateness fee multiplier seems off

### ISSUE THREAD

**Issue by DeinKoenig** [daleao/modular-overhaul#119]
So I've got a problem when taxes can't be paid in full on the 2nd of each month. Instead of an additional standard 5% lateness fee on top it seems to multiply it by a ridiculous amount. It only happens if taxes can't be paid in full otherwise it charges whatever the letter is telling me. 
The last time I couldn't pay it said something around 300k left but charged me 1,5million over the course of a few days.

**Comment by DeinKoenig** [comment]
I did some testing with a new farm and the CJB mod. 
If I cant pay taxes on the 2nd and sell enough to clear my debt on the 3rd it charges me my whole income minus the oustanding debt. Didnt sell anything else and waited for the next month. It now says my income was equivalent to the previous oustanding debt. 
I'll attach my SMAPI log. In this scenario I had an oustanding debt of 1156g for summer. Sold around 45k on the 3rd of fall only to be left with 1156g on the 4th. Season income for fall is 1156g (instead of 45k) and I'm taxed according to that amount. 

The tax logs for these two month are close to each other near the end of the SMAPI log.
https://smapi.io/log/22e0372389fc4e22857c7883d70c3efe

**Comment by daleao** [comment]
PR will be merged manually in local build. Thanks for the fix.
