### ISSUE TITLE
Mod crash 3.1.2

### ISSUE THREAD

**Issue by reedtanguerra** [daleao/modular-overhaul#12]
I install by deleting everything out of the MARGO folder except my config file & copying in the new files, so I don't think this is a user error type problem? The CommunityToolkit.Diagnostics DLL file is definitely there in my folder.

Smapi log: https://smapi.io/log/6a22fbf12d8c41cfa8dd82291e630cd7

**Comment by daleao** [comment]
Looks like you're using Vortex. Can you try without it?
It definitely loads fine from SMAPI directly.

**Comment by reedtanguerra** [comment]
Ok. I tried launching SMAPI via Steam, and also directly from the exe on my hard drive. I tried uninstalling & reinstalling SMAPI 3.18.4. Same crash message encountered in all three tests. I upgraded from build 3.1.1, which works perfectly no errors. I rolled back to 3.1.1 and continued playing my mod setup just earlier this evening. From the change log, it didn't look like you changed anything material so really not sure what's happening here?

**Comment by daleao** [comment]
What happens if you just replace `DaLion.Overhaul.dll` and `assets` folder from 3.1.1 with the ones from 3.1.2?

**Comment by reedtanguerra** [comment]
I get what you're saying about Vortex, but I don't install MARGO using Vortex. I'm directly copy pasting the files from the zip file, so I don't see how Vortex would be causing this particular crash? MARGO is one of the few mods where I do that because it doesn't work well with Vortex like you note in your instructions as well. I respect the modding community's dislike of Vortex, but it's been my experience that the vast majority of mods have no problems with installing via Vortex. :)

The crash message looked the same but I admit I didn't keep the logs, so I will reexecute and bring you smapi logs.

**Comment by reedtanguerra** [comment]
3.1.2 Steam launch: https://smapi.io/log/a073d22e6f1e4a6a8a51c6bf2c5888b2
3.1.2 SMAPI exe launch: https://smapi.io/log/2f45f0ccf6c9429f8d06fc04f29414c3

Replace 3.1.1 DaLion.Overhaul DLL & assets folder with 3.1.2, all other mod files remain 3.1.1, launch from SMAPI exe (boots no error messages): https://smapi.io/log/34c0f58ace25429584f724ed4cd7a2b1

**Comment by daleao** [comment]
I suppose the next logical test would be to just install 3.1.2 and replace the CommunityToolkit.Diagnostics.dll with the one from 3.1.1.

Very strange though, as they should be equivalent. You can check this by calculating the [MD5 hash](https://md5file.com/calculator) for each file (3.1.1 and 3.1.2) and comparing.
If the values are not identical then there could indeed be a problem.

**Comment by reedtanguerra** [comment]
The top one is Community.Toolkit.Diagnostics.dll 3.1.2, bottom one 3.1.1. I'm afraid I have no idea what I'm looking at though hehehe.
 
![MD5 Hash test](https://github.com/daleao/modular-overhaul/assets/35355384/f9d42fc6-9269-4fe1-aca0-41bf152fdd02)

**Comment by daleao** [comment]
Confirms they are different.
Did you confirm if 3.1.2 works but replacing just that one file?

**Comment by reedtanguerra** [comment]
Replace 3.1.2 Community.Toolkit.Diagnostics.dll with 3.1.1, all other mod files 3.1.2, launch from Smapi exe (uh oh now it's the other DLL crashing) : https://smapi.io/log/02a08f56debf49e5b653550f5d086a2b

**Comment by daleao** [comment]
Interesting. Thanks for doing the tests.
For now I suggest you keep using the previous way (replacing 3.1.1 dll and assets folder).

**Comment by reedtanguerra** [comment]
Will do! Sorry if this is caused my something unique to my setup. I will happily ditch whatever other mod if that's the case. MARGO is wonderful and a must have! :)

**Comment by daleao** [comment]
Figured out the issue:
"you can trivially fix it by copying MARGO's newer CommunityToolkit.Diagnostics.dll to AtraCore."
It's caused because AtraCore is using the same file, but a different version. The same applies to the other dll FastExpressionCompiler.

**Comment by reedtanguerra** [comment]
Hahaha oml that's a silly problem. I'll go leave a comment on Nexus. Atracore is a requirement of a requirement for folks playing with DestyNOVA's two NPCs from East Scarp. Thank you so much for helping sort it out!

**Comment by reedtanguerra** [comment]
Can confirm replacing Atracore's files with yours allows 3.1.2 to boot up with no problems! Yay!

**Comment by Ange1icAura** [comment]
Needed this. Thank you!

**Comment by reedtanguerra** [comment]
@daleao Atra has released a 9/17 Atracore hotfix updating to your 3.1.2 versions of the DLL I believe. We now have a reversed incompatibility situation beginning with 3.1.3 up
