### ISSUE TITLE
Multiplayer Farmhand Prospector Hunt Bug

### ISSUE THREAD

**Issue by veselin-antonov** [daleao/modular-overhaul#121]
When a farmhand starts a prospector hunt, the game doesn't make the new hot-cold sounds and there is some errors in the SMAPI console. The functionality works as expected for the host.

These are the logs from the current game session: [Farmhand](https://smapi.io/log/afa82ef8bc054cab970c349fc2d9df39) [Host](https://smapi.io/log/e3ea949f69434df3b44a8018978b9712)

**Comment by daleao** [comment]
Should be fixed in 4.1.6.
