### ISSUE TITLE
Fishing level has exceeded the upper limit

### ISSUE THREAD

**Issue by municat** [daleao/modular-overhaul#122]
I opened the skill experience multiplier. When I was fishing at level 17, I caught the Summer Fish King. My fishing level exceeded level 20 and reached level 21. When I reopened the skill interface, my fishing level changed to level 17 with 15000 experience. However, from level 17 to level 18, only 5000 experience was needed, so my fishing level could never reach level 20 ...     QAQ
Is there any way to reset skill level or experience to zero？

**Comment by daleao** [comment]
Sorry but I did not understand any of that. Probably something was lost in translation.
Use the console commands of the mod to reset your skill if you'd like (`prfs help`).
