### ISSUE TITLE
Slingshot profession at Lvl 5 Combat broken in Multiplayer

### ISSUE THREAD

**Issue by Ceepert** [daleao/modular-overhaul#124]
When anyone chooses the "Rascal" profession in a (online not sure if splitscreen too) Coop session and try to select a slingshot with the mousewheel it basically skips the slingshot and moves to the next item.
Manual selection by pressing the number still works, but anytime the player shoots a big nullrefference error shows up in the console. Also the 2nd slot for ammo that Rascal should provide is not displayed. The room for it is made, but nothing is displayed there.

This does not happen in Singleplayer and it happens to both the Host and anyone joining.

Havent tested it with any lvl10 profession in that tree as this just happened in our Coop game and we just wanted to know if we can avoid it, but it seems to be an issue with the multiplayer part as it even happens if you are solo in a coop game without anyone else connected.

**Comment by daleao** [comment]
Will have to close this due to inactivity.
If you still experience this issue, most likely  you can fix it by trashing your slingshot and spawning a new one.
