### ISSUE TITLE
Socializing, Binning, Archaeology skill levelling up past 10 without prestige

### ISSUE THREAD

**Issue by kumas-K** [daleao/modular-overhaul#125]
Hello.
Skills using the prestige system have a skill levelling up past 10 without prestige

[Socializing Bug](https://www.nexusmods.com/stardewvalley/mods/14142?tab=bugs)

**Comment by daleao** [comment]
For the purposes of this mod, "prestige" refers to the professions you gain at levels 15 and 20.

With that light, can you please rephrase your issue, provide examples, screenshots, and a log. I'm also not sure where you were trying to link to.

**Comment by kumas-K** [comment]
> I think what they're trying to say is we still get exp when we still don't have four ribbons

@daleao 
Right, this is what I wanted to talk about.

**Comment by daleao** [comment]
Is this behavior only with custom skills?

**Comment by kumas-K** [comment]
@daleao 
That’s right, there is a problem only with custom skills.

**Comment by daleao** [comment]
Should be fixed in 4.1.7.
