### ISSUE TITLE
margo crashes while editing weapon tilesheets

### ISSUE THREAD

**Issue by broccolibritt** [daleao/modular-overhaul#126]
https://smapi.io/log/93924b2df9184740a8d65d15ab030eb3

The mod crashes upon loading smapi when editing the Tilesheets/weapons asset, I've tried looking it up but can't find anyone with my issue so I've resorted to posting it here. Sorry if it's an easy fix or something I'm not too bright with this sorta stuff

**Comment by daleao** [comment]
I guess one of your mods is changing the size of the weapon tilesheet before MARGO has a chance to patch it.
I don't know of any mod that would do that, so I can't tell you which mod. Probably isn't any JA mod.
Point is, you have a mod conflict. And there's no easy solution unless you can identify which mod is causing the conflict.
To do that you will have to gradually remove your mods until the issue goes away. The last mod you removed is then the conflicting one. The Reporting Bugs & Issues section of the README explains this process a little better.

To be honest though, if you have mods with custom weapons you probably should not be using the Weapon Overhaul feature of the Combat module. My suggestions would be to either uninstall any modded weapons and use the Weapon Overhaul, OR disable the Weapon Overhaul.
