### ISSUE TITLE
Welcome Message Always Appears on Startup

### ISSUE THREAD

**Issue by VanguardTimaeus** [daleao/modular-overhaul#127]
Playing on Steam Deck through Linux. The welcome message appears every time the game is started up, even after playing through several days. Trying to edit the mod's config through Generic Mod Config Menu only causes the message to reappear, making me unable to actually edit it without manually editing the config file. This issue persists even after removing all mods except MARGO and its dependencies. Playing through Proton also does not resolve the issue. The mod still loads in game as normal.

Here is my log:
https://smapi.io/log/a44fd8eea6b54e8aaf362470ae6f293b

**Comment by mattyicesr** [comment]
Happening to me as well

**Comment by daleao** [comment]
Tried setting `LaunchInitialSetup` to false?

**Comment by VanguardTimaeus** [comment]
It seems to fix the window opening on startup, but the window still appears when I try to open the config menu.

**Comment by VanguardTimaeus** [comment]
Sorry. Didn't mean to close the issue.
