### ISSUE TITLE
Dig spots are broken in latest version (archaeology skill incompatibility?)

### ISSUE THREAD

**Issue by Tzasame** [daleao/modular-overhaul#129]
Dig spots are infinite and (I believe) aren't dropping their modded archaeology skill drops. They worked properly prior to 4.1.7.

Archaeology skill -- https://www.nexusmods.com/stardewvalley/mods/15793

SMAPI log -- https://smapi.io/log/890445b84d644f2dbcbfd5cf1786142a

**Comment by daleao** [comment]
Would you please test the attached version below?
[ModularOverhaul 4.1.8.zip](https://github.com/daleao/modular-overhaul/files/13668187/ModularOverhaul.4.1.8.zip)

**Comment by Tzasame** [comment]
Dig spots are working as intended again with that version. Thank you.
