### ISSUE TITLE
Dwarven Legacy Quest Completion Causes Complete Crash on Attempting to Complete - Version 3.1.2

### ISSUE THREAD

**Issue by UnmadeThoughts** [daleao/modular-overhaul#13]
As the title suggests, I've run into a consistent issue while running Version 3.1.2 regarding the Dwarven Weapons questline (Started with QuestID 144701).

This save has both Modular Gameplay Overhaul & Stardew Valley Expanded.

After receiving the initial blueprint and processing the initial event with Clint (The one where he informs you that he'll need a couple of days to look over the blueprint, and that you should check back with him tomorrow), the game crashes abruptly (and forces an alt-f4 to close, otherwise the game will freeze my entire computer) when trying to speak to Clint while he's behind his counter, when (presumably) enough time has passed for that segment of the quest to be completed.

The game plays the Quest Complete chime sound effect before freezing completely, directly after talking with Clint with the Dwarven Legacy Quest active in my journal.

After reading the crash log (provided below), it seems to potentially be a draw/redraw request error of some kind, though I'm unsure of the specifics (as I'm unsure about the processes happening behind the scenes).

The file is currently on Spring 2 Year 2, and I have the Hero's Journey Quest active & The Blade of Ruin in my inventory as well (in case it's relevant). I'm also post-marriage, but have neither the Community Center nor Ginger Island unlocked/completed.

While the game is still in a playable state (as long as I just entirely quarantine myself from Clint), any help to solve the problem is much appreciated!

If I missed any relevant information, please let me know so I can provide it ASAP!

The aforementioned Crash Log is listed below:

[SMAPI-crash.txt](https://github.com/daleao/modular-overhaul/files/12633243/SMAPI-crash.txt)

**Comment by daleao** [comment]
Use the [3.1.1-DwarvenLegacyFix](https://github.com/daleao/modular-overhaul/releases/download/3.1.1/ModularOverhaul.3.1.1-DwarvenLegacyFix.zip) release until the quest is completed.
