### ISSUE TITLE
Social Skills Reset

### ISSUE THREAD

**Issue by Spirit27** [daleao/modular-overhaul#132]
My social skills are reset after updating to the latest version of this mod.

**Comment by daleao** [comment]
I have no idea what that means.

**Comment by InkDragon** [comment]
I believe it is in reference to this [mod](https://www.nexusmods.com/stardewvalley/mods/14142)

**Comment by Spirit27** [comment]
Hi, yes I'm sorry. I am referring to the socializing skill. I will send my SMAPI log.

**Comment by daleao** [comment]
Can you just use the console commands to set the level you had before?
Type in the console window `prfs set_levels socializing X` where X is the level you want.

**Comment by Spirit27** [comment]
I just tested with the newest version, and 4.2.0 seems to fix my issue. Thank you!
