### ISSUE TITLE
Editing mod options in GMCM causes some stabbing swords to stop stabbing

### ISSUE THREAD

**Issue by Zelly9191** [daleao/modular-overhaul#134]
editing the modules that have boxes where you can type things and saving will remove all spaces from those fields thus breaking the functions of numerous things.

i noticed this happening when i couldn't stab with some swords i should be able to.

ill upload my config as proof. and if you need the log let me know ill reproduce this and send that too.

[config.json](https://github.com/daleao/modular-overhaul/files/13691208/config.json)
 wasn't sure weather to report this to GMCM or here.

**Comment by VanguardTimaeus** [comment]
I'm having the same issue. It seems to also break the list of machines for the Artisan perk.

**Comment by daleao** [comment]
Can't reproduce.
I've added new boxes and edited existing boxes in both Stabbing Swords and Artisan Machines. Space were not removed.

**Comment by VanguardTimaeus** [comment]
I made a quick [video](https://youtu.be/GxWS6UQv7F8?si=P2eHbBNIFsCrfgGH) that gives some additional info and demonstrates how to replicate the issue. Please let me know if anything else is needed. (Also excuse my cat. He doesn't like when I talk to myself. Haha)

**Comment by Zelly9191** [comment]
I can confirm what was shown in the video. 
My apologies for my delayed response. I only just got this now.

I can confirm I'm running on Linux as I'm using the steam deck.
If You don't have access to a way to test on Linux. I'm fully willing to assist by testing.

**Comment by daleao** [comment]
Appreciate the video.
"Steam Deck" was the key insight here.
This version should fix it:
[ModularOverhaul 4.2.1.zip](https://github.com/daleao/modular-overhaul/files/13699852/ModularOverhaul.4.2.1.zip)

**Comment by VanguardTimaeus** [comment]
This solves the issue for me. I appreciate all your help. Thank you!
