### ISSUE TITLE
Visual Conflict Issue with MARGO and ItemBags

### ISSUE THREAD

**Issue by wibbelkind** [daleao/modular-overhaul#136]
![Screenshot 2023-12-16 180253](https://github.com/daleao/modular-overhaul/assets/154011969/7091dc83-246a-402f-9a2c-32044e420fee)
So I updated MARGO today for the first time in... ages. And now I'm having a weird glitch with another mod I'm using, called [Item Bags](https://www.nexusmods.com/stardewvalley/mods/5382). The mod supplies a variety of item bags (as shown in the screenshot) and you can gather them in Omni Bags. Since I updated MARGO today, all Omni Bags get displayed as roe.

I managed to recreate the issue on a new safefile, with only the two mods installed, so it seems to me it's only an issue between the two mods.

SMAPI log: https://smapi.io/log/c5f4ce0358bc4002a23aa5c52028b80a
SMAPI log with patch summary: https://smapi.io/log/ea356aa13ef142ffaf1c58a6bb928b13

**Comment by daleao** [comment]
What does it usually look it?

**Comment by wibbelkind** [comment]
![omnibag](https://github.com/daleao/modular-overhaul/assets/154011969/3700147d-3d0a-4554-93a5-e4154e0baa83)
Like this...

**Comment by daleao** [comment]
Looks like your mod is using the Pirate profession icon for this item.
MARGO Professions changes that icon for the Aquarist profession.
Ideally your mod would not be using a profession icon for an item.
You should ask the mod author to implement it as a separate texture.
If want to manually work around this, you can open [this](https://github.com/daleao/modular-overhaul/blob/main/assets/sprites/interface/professions.png) file in MARGO's `assets` folder and paste the pirate treasure icon over the Roe icon.
