### ISSUE TITLE
Shift + F12 didn't call out the config at title screen

### ISSUE THREAD

**Issue by xiaoleiwenm** [daleao/modular-overhaul#14]
Not sure how to change the config in game now TT

**Comment by daleao** [comment]
Just navigate to it normally via GMCM.
There should be a cog button in the title screen, and a "mod settings" button in-game at the bottom of the settings menu.
Make sure you don't have another mod using the same key combination.

**Comment by Rais-Codex** [comment]
If there is no config, try installing the latest version of Custom Ore Nodes. That mod may be required only by one of the modules, but it seems to be treated as a requirement for the mod to work.

**Comment by daleao** [comment]
> If there is no config, try installing the latest version of Custom Ore Nodes. That mod may be required only by one of the modules, but it seems to be treated as a requirement for the mod to work.
> 

It's not a requirement for the mod. But if you do install it and it's an old version, then SMAPI will complain that you need to upgrade.

**Comment by xiaoleiwenm** [comment]
I'm using latest Custom Ore Node.

Anyway, I noticed red lines when using the latest Margo, probably there is something wrong that made it not appearing under my GMCM:

https://smapi.io/log/3941dc7e3ef74f9791ce0614423e71c9?Levels=warn%7Eerror%7Ecritical

Reverting back to 3.1.1 seems can load it properly.

**Comment by smeagol136** [comment]
I just updated to 3.1.2 and had the exact same issues: 1) couldn't find the mod under the GMCM to change config; 2) updated custom ore nodes after reading this post; 3) *only having updated custom ore nodes*, got the exact same red lines as [xiaoleiwenm] and still can't edit the config.

Hands down my favourite stardew mod btw

**Comment by daleao** [comment]
If you can't find a mod in GMCM, or the GMCM shortcut is not working, it's not because the GMCM is bugged; it's because the mod itself didn't load _at all_.
Read your logs, and 95% of the time you will be able to figure out the issue on your own, or at least have a better idea of what to say when reporting the issue here.

Your issue is a repeat of [Mod crash 1.3.2](https://github.com/daleao/modular-overhaul/issues/12).
