### ISSUE TITLE
Some ring synthesis errors

### ISSUE THREAD

**Issue by Jumping-notes** [daleao/modular-overhaul#140]
Some ring synthesis errors, no material consumption.
And their introductory text sometimes goes outside the framework.

**Comment by daleao** [comment]
Can you be more specific? Which rings?

**Comment by Jumping-notes** [comment]
When I made the glowstone ring it only consumed solar essence and void essence, the other rings I haven't tested yet.

**Comment by daleao** [comment]
Should be fixed in this version:
[ModularOverhaul 4.2.2-Debug.zip](https://github.com/daleao/modular-overhaul/files/13814013/ModularOverhaul.4.2.2-Debug.zip)
