### ISSUE TITLE
Crab pots cannot produce 2× per day.

### ISSUE THREAD

**Issue by lcb0218** [daleao/modular-overhaul#141]
I keep the mods the lastest version. when i get Luremaster, crab pots can only produce twice the first time. Every time i start the game, they produce twice only once. I test the game just with Margo and the dependencies. I wonder if it is a bug or i misunderstood the mechanism.

**Comment by daleao** [comment]
I believe this should fix the issue.
 Would you be so kind to give it a test?
[ModularOverhaul 4.2.2-Debug.zip](https://github.com/daleao/modular-overhaul/files/13813760/ModularOverhaul.4.2.2-Debug.zip)

**Comment by lcb0218** [comment]
> I believe this should fix the issue. Would you be so kind to give it a test? [ModularOverhaul 4.2.2-Debug.zip](https://github.com/daleao/modular-overhaul/files/13813760/ModularOverhaul.4.2.2-Debug.zip)

The problem has been solved. Thank you very much
