### ISSUE TITLE
Mammonite weapon enchantment subtracting money when killing enemies

### ISSUE THREAD

**Issue by Exaxxion** [daleao/modular-overhaul#142]
Using MARGO v4.2.1, I enchanted my Blade of Dawn at the Forge and randomly got Mammonite. I looked up the description and it sounded cool:
> Attacks that would leave an enemy below 10% max health immediately execute the enemy, converting the remaining health into gold. This threshold increases by 1% with each consecutive takedown, resetting when you take damage.

However it seems to be bugged because every enemy I defeat causes my money to _decrease_. 

This is the complete opposite of the effect I expected based on the description. If this isn't a bug, please clarify the description to indicate it's a curse that robs you of money in exchange for executing the enemy. Thankfully I happened to notice this quickly (only lost several thousand gold on my save before loading the next day with cheats to confirm I wasn't imagining it).

Note how before I kill the slime my money is at 268348
![Screenshot at 2023-12-29 19-37-54](https://github.com/daleao/modular-overhaul/assets/11907282/fbe50256-e554-45e2-a17b-d38cb7b6c492)

...and after killing it it drops to 268187.
![Screenshot at 2023-12-29 19-37-59](https://github.com/daleao/modular-overhaul/assets/11907282/ce229780-9f25-4e79-9e5c-c8fa4557d267)

**Comment by daleao** [comment]
Probably a bug caused by overkilling the enemy.
