### ISSUE TITLE
Other players crash on connection load into multiplayer with existing character

### ISSUE THREAD

**Issue by TheRedstoneMind** [daleao/modular-overhaul#143]
I was playing with my boyfriend and when he created a new character on my save in multiplayer we could play normally, but when we ended for the day and then wanted to play the next day, he couldn't join with the existing character, because he got an error in SMAPI that originates from MARGO. The error is cause by SMAPI not recognizing something to do with dagger enchantments. It can only be solved by destroying the multiplayer house and rebuilding it again to delete his old character and him creating a new one. But even after making a new character it will suffer the same fate the next day. The same happens on any save file.

https://smapi.io/log/b06d4b2e2958449eb6c6123a282f9aa3

**Comment by daleao** [comment]
Z

**Comment by daleao** [comment]
Make sure you both have exactly the same mods and the same config settings. Have him trash any daggers he is holding.

**Comment by TheRedstoneMind** [comment]
He has no daggers and he has exactly the same configs and mods as me. Plus how could he trash the daggers when he can't even join?

**Comment by TheRedstoneMind** [comment]
Plus the log is his, mine has no errors.

**Comment by TheRedstoneMind** [comment]
We have tried something, and it seems that a dagger I had in my inventory was causing him to crash. After I destroyed it in the trash he could join and play.

**Comment by daleao** [comment]
Would you try spawning the same dagger again with CJB to see if it's a persistent or a one-off issue?

**Comment by TheRedstoneMind** [comment]
I don't have the item spawn part of CJB but we can try by getting a new dagger. We literally just caught a trident dagger while fishing and we are in the first year and just finished the egg festival.
