### ISSUE TITLE
The ruined blade forces itself to use

### ISSUE THREAD

**Issue by alphinec** [daleao/modular-overhaul#144]
I've started to use this mod lately and I love it. the problem I have seen is I can't stand against a ruined blade dot so I'm using it against high HP enemies only and I'm using a normal sword for normal times. but when I try to select my sword, the Ruined Blade in the inventory is usually selected. Is it a feature or a bug? I checked all the forums and didn't find any information about this. (I don't use the option about leaving it in a chest. I don't want to leave my ruined blade in a chest because if I can't leave my sword it feels like more cursed.)
![Screenshot_6](https://github.com/daleao/modular-overhaul/assets/155338099/4862b383-2da6-4a43-90a4-ba6ea90cc055)
if i spam 3, after a couple try 1 becomes selected

**Comment by daleao** [comment]
It's a feature of the blade's curse.
See "What is the Blade of Ruin's curse?" in the [CMBT FAQ](https://github.com/daleao/modular-overhaul/tree/main/Modules/Combat#faq).
