### ISSUE TITLE
infinite toolbar scrolling with scroll to blank mod 

### ISSUE THREAD

**Issue by Baboulinet74940** [daleao/modular-overhaul#146]
found an issue between MARGO mod and the scroll to blank mod https://smapi.io/log/6e1b2648754f422b9568f03e05bb2642
(ctrl+F and type Scroll to blank the logs are huge since i have so many mods x))
just letting you know in case you can fix it or if that can only be fixed by the guy who made scroll to blank (which i dont think is gonna happen :')) if not that's fine ill just not use scroll to blank even though it helps in heavy modded playthrough so that we can use the keybinds that are used for the toolbar for something else ^^
have a nice day and happy new year

**Comment by daleao** [comment]
I don't have any issue just from installing that mod.
Maybe you did something specific to trigger an issue, or maybe you have a different conflict.
Please make sure you can reproduce the issue reliably on a minimal modlist.
See [Reporting Bugs and Issues](https://github.com/daleao/modular-overhaul?tab=readme-ov-file#reporting-bugs-or-issues).
