### ISSUE TITLE
The game startup process crashes

### ISSUE THREAD

**Issue by Jumping-notes** [daleao/modular-overhaul#148]
https://smapi.io/log/295ec38d2d074a1fad9190214fd0541d
I heard about this problem from others and tried to reproduce it successfully.
Since the last message in the log after startup is Margo, I am sending it here.
The strange thing is that it doesn't appear every time, but occasionally.

**Comment by daleao** [comment]
I don't understand. There are no errors in the log. What exactly is the trigger condition? Is it something about this specific list of mods?

**Comment by Jumping-notes** [comment]
This error is suspected of updating the mod and using the old config. json raised. When I deleted it it returned to normal.
Here he sent me another save crash log of mine that he said appeared after resetting the skill several times.
I suspect it's caused by resetting other mods' abilities.
https://smapi.io/log/27cd4bfbe84e4c91aef1e07895fa32f6
Also, I noticed an error with i18n in the Prestige Settings. Four key values are not matched.
