### ISSUE TITLE
Question on limits of Producer/Yieldmeister profession

### ISSUE THREAD

**Issue by mj717** [daleao/modular-overhaul#149]
Sorry, this isn't a bug report so much as a question (hope it's OK to post here, sorry if it's not). I have the Producer profession (prestiged) but have noticed that buying and filling up deluxe barns and coops has stopped increasing the price of artisan goods for me. Is there a ceiling on how much more artisan goods can be worth?

**Comment by Exaxxion** [comment]
Per the description in the Professions Readme, Producer gives a 5% additive bonus value to animal products for each Deluxe Coop or Deluxe Barn that is completely filled with animals, with no limit to the multiplier. Prestige affects only the animal production rate (2x -> 3x).

[The code](https://github.com/daleao/modular-overhaul/blob/44c6ee7499dbba1b21f3a34321e998d5db872dc7/Modules/Professions/Extensions/FarmerExtensions.cs#L263) appears to reflect this intention.
