### ISSUE TITLE
Saboteur profession causing game/character to freeze

### ISSUE THREAD

**Issue by mj717** [daleao/modular-overhaul#150]
Hi, I'm having an issue with the Saboteur profession. I'm getting an error (see SMAPI) about the poison animation when I start killing monsters. The error occurs both when I kill monsters using the tractor from the Tractor Mod and when I kill monsters like normal, sans tractor.

Unfortunately, the error is causing my game to freeze for long periods. At times, it is also causing my character to become stuck with their sword above their head, as though the weapon animation has become stuck. When this happens, I can warp using CJB Cheats but cannot move my character, switch to a different item in the hotbar, or do other things like open Chests Anywhere. Typically, I can wait for a few minutes and my character goes back to normal, but I did once have it crash from it.

SMAPI: https://smapi.io/log/2a64d7dc526f4ea785132f6affb98fbb

**Comment by daleao** [comment]
Oh woops. The poison texture is still tied to the combat module, that's why it's "missing".
For now, if you enable combat then it'll work (even if you uncheck all the features).
Obviously this is an oversight. Will be fixed on the next version.
Thanks for reporting.
