### ISSUE TITLE
Typo on Altar of Yoba.

### ISSUE THREAD

**Issue by EDekar** [daleao/modular-overhaul#151]
"Yoba's blessing, true heroes it shall fortify.
In **_Genoristy_** and Compassion, virtues to comply.
With Honor, Valor, Wisdom, their spirits amplify.
A prophecy unfolds, under Yoba's watchful eye."

Simple misspelling of generosity.

**Comment by daleao** [comment]
Oh my what a grotesque mistake.
Thank you for pointing it out.
