### ISSUE TITLE
Professions README typo

### ISSUE THREAD

**Issue by veselin-antonov** [daleao/modular-overhaul#155]
I suppose that this should say "5.5% slower"

![image](https://github.com/daleao/modular-overhaul/assets/63060339/6b6c7b7f-f3ab-4bdf-9b6d-90a9e7241302)

I want to also use the chance to ask if the requirement for multiplayer doesn't count (all ponds are taken into account, no matter the owner) if you have the Lax Ownership config option set to 'true'.

**Comment by daleao** [comment]
Yes.

**Comment by veselin-antonov** [comment]
Yes for the issue or the question..?

**Comment by daleao** [comment]
Yes to both.
