### ISSUE TITLE
Game crashing when talking to Clint after he translates the Dwarvish Blueprints

### ISSUE THREAD

**Issue by meijinlian** [daleao/modular-overhaul#158]
![error](https://github.com/daleao/modular-overhaul/assets/157839795/efed6a76-20c8-4366-88d6-dae088ab0413)

I wasn't able to copy the error code on SMAPI 'cause my computer crashed hard, I had to take a Screenshot, sorry.
So this is the second save that I run into this issue. I decided to fully delete the farm where I had this for the first time, and started a new farm, was playing it okay, went to ginger island and one of the chests I found the Dwarven Schematics. So I build friendship with the dwarf, I already had a good friendship vallue with Clint, and gave the blueprint to him. I checked everyday and he said "i didn't finish translating, maybe tomorrow" everyday, until I checked him again and the game crashes.
I'm not really good with modding, I have no idea how to solve this issue, And I don't want to lose other farm I had to work hard. I really love the mod and all the changes it does to the game, I don't want to uninstall it.

**Comment by daleao** [comment]
Please don't try to copy error messages or post screenshtos. [Upload your SMAPI log instead](smapi.io/log).
What version of MARGO did you begin this farm with?
Zip up your save folder and share it here so I may take a look.

**Comment by mediocrephilo** [comment]
I also had this issue, here's the SMAPI log!
[SMAPI-crash.txt](https://github.com/daleao/modular-overhaul/files/14076581/SMAPI-crash.txt)

**Comment by daleao** [comment]
Please read my previous message again.

**Comment by ly05772** [comment]
Yes, I have encountered the same problem, and I have encountered this problem in different archives.

**Comment by daleao** [comment]
Thanks but that contributes nothing. Would be great if people bothered to read the thread and supply the information I requested.

**Comment by mediocrephilo** [comment]
oops, sorry here it is 
[Sunwatch_281191250.zip](https://github.com/daleao/modular-overhaul/files/14104712/Sunwatch_281191250.zip)

**Comment by mediocrephilo** [comment]
Ok now I feel kind of dumb lol, I reinstalled MARGO and it fixed the issue. I thought I had installed the latest version but maybe not. I'll close the issue now. Sorry again!
