### ISSUE TITLE
Modular Overhaul doesn't load into GCGM

### ISSUE THREAD

**Issue by StreamingUnit** [daleao/modular-overhaul#16]
https://smapi.io/log/5481633736e449f0aaab336d2a94d5b9

Pretty much what it says on the tin, When I load 3.1.2 I cannot access the Config, but when I rollback to 3.1.1 It loads up fine, the error message below also appears

<html>
<body>

20:46:48 | ERROR | Modular Gameplay Overhaul | Mod crashed on entry and might not work correctly. Technical details: FileLoadException: Could not load file or assembly 'CommunityToolkit.Diagnostics, Version=8.2.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'. Could not find or load a specific file. (0x80131621) File name: 'CommunityToolkit.Diagnostics, Version=8.2.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'  ---> FileLoadException: Could not load file or assembly 'CommunityToolkit.Diagnostics, Version=8.2.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'.    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)    at System.Reflection.Assembly.LoadFrom(String assemblyFile)    at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)    at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)    at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)    at DaLion.Shared.Harmony.Harmonizer.ApplyImplicitly(Func`2 predicate)    at DaLion.Overhaul.Modules.OverhaulModule.Activate(IModHelper helper) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\OverhaulModule.cs:line 118    at DaLion.Shared.Extensions.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in C:\dev\sdv\mods\1.5\Shared\Extensions\Collections\EnumerableExtensions.cs:line 21    at DaLion.Overhaul.ModEntry.Entry(IModHelper helper) in C:\dev\sdv\mods\1.5\Modular Overhaul\ModEntry.cs:line 104    at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in SMAPI\Framework\SCore.cs:line 1810
-- | -- | -- | --

</body>
</html>

**Comment by daleao** [comment]
Repeat of [Mod crash 3.1.2](https://github.com/daleao/modular-overhaul/issues/12).
