### ISSUE TITLE
Skill level reset

### ISSUE THREAD

**Issue by huanmeng005** [daleao/modular-overhaul#160]
After the skill level reaches level 10, it will be reset to level 10 every time you re-enter the game. Is there any missing prerequisites or other problems?

**Comment by daleao** [comment]
What?

**Comment by huanmeng005** [comment]
Each skill level must be played to level 10 or above, such as level 15 or level 20. Then close the game and re-enter it and it will return to level 10.

**Comment by daleao** [comment]
Log please

**Comment by huanmeng005** [comment]
What to log into？
