### ISSUE TITLE
Fish Ponds Items Dissapear 

### ISSUE THREAD

**Issue by StardewMoody** [daleao/modular-overhaul#164]
Hello I recently placed an iridium quality King Salmon from Stardew Valley Expanded mod on the fish pond, after doing so the fish dissapeared and i empitied the fish pond to add an iridium quality eel. 

After it dissapeared too i used the commands:
-pnds reset_data
-pnds set_quality

which solved the problem for the session. After a day passed by when i loaded my save again to play the pond was once again empty. 
When i add a new eel to it it sends this message on the log:

[Modular Gameplay Overhaul] [PNDS]: System.IO.InvalidDataException: FishQualities data had incorrect number of values.
   at CommunityToolkit.Diagnostics.ThrowHelper.ThrowInvalidDataException(String message)
   at DaLion.Overhaul.Modules.Ponds.Patchers.FishPondAddFishToPondPatcher.FishPondAddFishToPondPostfix(FishPond __instance, FishPondData ____fishPondData, Object fish) in G:\modded\sdv\dev\main\margo\Modules\Ponds\Patchers\FishPondAddFishToPondPatcher.cs:line 95
The data will be reset.

I dont know what to do, but im alert to any suggestion, thank you and sorry!

**Comment by TJourney** [comment]
I've encountered this issue a few times as well, though each time I've encountered the problem it has manifested as some or all of the fish in a given pond spontaneously switching their quality to something else. It does not affect all of the ponds when it occurs, and doesn't always affect all of the fish in a given pond, but I've seen it affect ponds full of iridium Lingcod, iridium Sunfish, iridium Super Cucumber, iridium Midnight Squid, iridium Pike, iridium Grass Carp, and iridium Sturgeon.

Here's a screenshot from one occurrence :
![image](https://github.com/daleao/modular-overhaul/assets/20450216/3b7d8cb1-6a5b-4bc3-8164-336b5896a849)
This pond contained 12 iridium-quality Midnight Squid prior

**Comment by TJourney** [comment]
checking with `pnds print` for affected ponds:

```
pnds print
pnds print
[Modular Gameplay Overhaul] Lingcod pond's mod data:
        Fish qualities:
                - Regular: 3)
                - Silver: 0
                - Gold: 0
                - Iridium: 0

        The pond holds no items.:

        The pond has been checked today.
pnds print
[Modular Gameplay Overhaul] Lingcod pond's mod data:
        Fish qualities:
                - Regular: 3)
                - Silver: 0
                - Gold: 0
                - Iridium: 0

        The pond holds no items.:

        The pond has been checked today.
pnds print
[Modular Gameplay Overhaul] Midnight Squid pond's mod data:
        Fish qualities:
                - Regular: 5)
                - Silver: 1
                - Gold: 0
                - Iridium: 0

        The pond holds no items.:

        The pond hasn't been checked today.
pnds print
[Modular Gameplay Overhaul] Midnight Squid pond's mod data:
        Fish qualities:
                - Regular: 5)
                - Silver: 1
                - Gold: 0
                - Iridium: 0

        The pond holds no items.:

        The pond hasn't been checked today.
pnds print
[Modular Gameplay Overhaul] Sturgeon pond's mod data:
        Fish qualities:
                - Regular: 11)
                - Silver: 1
                - Gold: 0
                - Iridium: 0

        The pond holds no items.:

        The pond has been checked today.
pnds print
[Modular Gameplay Overhaul] Sturgeon pond's mod data:
        Fish qualities:
                - Regular: 11)
                - Silver: 1
                - Gold: 0
                - Iridium: 0

        The pond holds no items.:

        The pond has been checked today.
pnds print
[Modular Gameplay Overhaul] Woodskip pond's mod data:
        Fish qualities:
                - Regular: 12)
                - Silver: 0
                - Gold: 0
                - Iridium: 0

        The pond holds no items.:

        The pond has been checked today.
pnds print
[Modular Gameplay Overhaul] Sunfish pond's mod data:
        Fish qualities:
                - Regular: 0)
                - Silver: 2
                - Gold: 1
                - Iridium: 9

        The pond holds no items.:

        The pond has been checked today.
```

**Comment by daleao** [comment]
@StardewMoody can you please share your save and mods folders?

**Comment by StardewMoody** [comment]
Hello @daleao , sure i will be sending them. Im not sure how to send them so i will use WeTransfer if that is okay. 

Mods folder: https://we.tl/t-KZJ6X4QWCl
Save File: https://we.tl/t-8H8Y4kUWCi

Thank you very much!

**Comment by daleao** [comment]
Looks to be caused by Visible Fish.
Occurs even without MARGO installed.

**Comment by StardewMoody** [comment]
Thank you, i uninstalled the visible fish mods and no fish seem to be missing now. Even after i leave the area multiple times (leaving farm area usually made almost all fish dissapear). You are amazing!
