### ISSUE TITLE
Using the Scroll Wheel causes the inventory to scroll non-stop

### ISSUE THREAD

**Issue by JannisJo** [daleao/modular-overhaul#165]
When using scroll wheel to switch items, the selected items scroll extremely quickly, until the scroll wheel is returned to the initial position. While this happens, the game is frozen with the character animation stopping, and time frozen. I was also able to stop the scrolling by using right-click and it would set the selected item to the initial item before I started scrolling.

Is not caused by a mod conflict as I opened SMAPI with only SpaceCore and MARGO and the issue persists. The issue also exists in a new file, however not sure if old files would be affected as I didn't have any old files to test it on.

Just to be sure it was not an issue with hardware, I opened the game with no mods and there was no issue. I also tried only removing MARGO from the mods folder while having all the other mods I play with enabled, and there was also no issue.

I made sure to be on the most recent version for SMAPI, SpaceCore and MARGO.

https://smapi.io/log/320f4070a886411d8245ca432d769880

**Comment by JannisJo** [comment]
After a bit of looking at the logs myself, it seems that something in the Combat Module is causing an issue, so I tried disabling only the Combat Module and it seems to have stopped the issue.

Hopefully this helps in tracking down the problem.

**Comment by JannisJo** [comment]
Okay I'll test it tomorrow, won't have access to the game til then

**Comment by JannisJo** [comment]
Hmm, not sure what happened, but something weird is going on.

First I tested with only SpaceCore, Json Assets, MARGO, and Expanded Preconditions Utility, the issue no longer exists, and there is no Infinity Band in my inventory.

Then, I tested again with only SpaceCore and MARGO just to see, and the issue still exists, so it seems that Json Assets has somehow fixed it.

The weird thing is, when I initially tried MARGO, I already had Json Assets and Expanded Preconditions Utility in my mod folder, so I tried launching again with all my mods enabled and magically the issue no longer happens? I didn't update either of Json Assets or EPU so it shouldn't be a version issue.

So for some reason it's working fine now.

**Comment by JannisJo** [comment]
The only reason I can think off is that, a few days ago, I played without updating most of my mods. Perhaps only SpaceCore and MARGO has the issue, and one of the mods is somehow conflicting with Json Assets or EPU which also caused the issue, and after updating most of my mods the conflict no longer exists.

Here's the logs with MARGO, Json Assets, EPU and SpaceCore only:
 https://smapi.io/log/9e72630265814c1b8c346f46210207d8

Here's the logs with all mods I use: (probably not useful because I didn't have the logs with all mods when the issue DID exist)
https://smapi.io/log/b32f68e0591b407e85df074877fe39f8

**Comment by daleao** [comment]
Glad it's fixed. You log specifically mentioned the Garnet gemstone which is added via Json Assets.
I checked the code and there didn't seem to be any failsafe in case the player does _not_ have JA, so I will be adding that and releasing another final update. Should avoid this in the future.
