### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by MrMagoozor** [daleao/modular-overhaul#166]
Lifting the Ruined Blade's curse segment 'Prove your Valor' does not take into account eradication goals if using the mod 
[Custom Adventure Guild Challenges](https://www.nexusmods.com/stardewvalley/mods/2301). Even the vanilla challenges do not count as complete.

![Screenshot 2024-02-08 235249](https://github.com/daleao/modular-overhaul/assets/17347275/cc95b678-9104-4312-b623-5694ccc8649f)

![Screenshot 2024-02-08 235348](https://github.com/daleao/modular-overhaul/assets/17347275/d9c2c1ce-ae4a-420f-a5e9-487cd2b8cd00)

**Comment by daleao** [comment]
Sorry but I have no intention of adding compatibility for a mod that hasn't been updated in 4 years.
And you definitely should not be using a SMAPI mod that old (content packs and such are fine).

**Comment by MrMagoozor** [comment]
Indeed, understandable. It has been updated by fans, but it is your prerogative. Thanks for all your work regardless.

Considering the situation, is there a way I can manually set the quest as complete when I do reach the goal?

**Comment by daleao** [comment]
You can also complete this virtue by digging a certain number of floors in the Skull Caverns without using stairs (between 10 and 40, depending on difficulty setting), or by reaching the Treasure Cave in the Crimson Badlands if you have SVE.

If you want to manually give yourself a point in the quest you use console commands (`cmbt adv valor`).
