### ISSUE TITLE
Errors that occur when using combat

### ISSUE THREAD

**Issue by ungmang** [daleao/modular-overhaul#169]
The sentences may be strange because a translator is used.
I am using a pc.
There is no problem using margo.
However, if you only use combat, an error will occur.
help me

This is my error log.
https://smapi.io/log/63d104e4a26c4a0db1a2fd1b905e6df2

**Comment by daleao** [comment]
If you are talking about this error;
`[Harmonizer]: Failed to apply Game1CheckForEscapeKeysPatcher.`
Then you can safely ignore it.
