### ISSUE TITLE
Mod crashes before the game starts

### ISSUE THREAD

**Issue by uva-passa** [daleao/modular-overhaul#17]
i'm not very tech savvy so apologies if this is a bit of a silly issue!

I downloaded the new version of the mod and deleted the old version of MARGO, when I open the game the mod crashes and my game doesn't work. I've tried copying folders from my old MARGO file into the new one, changing a folder in Atracore etc. but nothing is working. Please help I do love this mod. 

SMAPI Log: https://smapi.io/log/caf9e38aee0d41f19c3ea87bd165a757

**Comment by daleao** [comment]
Either delete you config.json, or change the value of all "DeductibleXXXX" from `true`/`false`  to `0.0`/`1.0`.
