### ISSUE TITLE
FileLoadException on mod load

### ISSUE THREAD

**Issue by N3rdGirl** [daleao/modular-overhaul#18]
Upon loading the game the mod crashes with this message spat out in the console.

21:07:14 | ERROR | Modular Gameplay Overhaul | Mod crashed on entry and might not work correctly. Technical details: FileLoadException: Could not load file or assembly 'CommunityToolkit.Diagnostics, Version=8.2.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'. Could not find or load a specific file. (0x80131621) File name: 'CommunityToolkit.Diagnostics, Version=8.2.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'  ---> FileLoadException: Could not load file or assembly 'CommunityToolkit.Diagnostics, Version=8.2.0.0, Culture=neutral, PublicKeyToken=4aff67a105548ee2'.    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)    at System.Reflection.Assembly.LoadFrom(String assemblyFile)    at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)    at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)    at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)    at DaLion.Shared.Harmony.Harmonizer.ApplyImplicitly(Func`2 predicate)    at DaLion.Overhaul.Modules.OverhaulModule.Activate(IModHelper helper) in C:\dev\sdv\mods\1.5\Modular Overhaul\Modules\OverhaulModule.cs:line 118    at DaLion.Shared.Extensions.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in C:\dev\sdv\mods\1.5\Shared\Extensions\Collections\EnumerableExtensions.cs:line 21    at DaLion.Overhaul.ModEntry.Entry(IModHelper helper) in C:\dev\sdv\mods\1.5\Modular Overhaul\ModEntry.cs:line 104    at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in SMAPI\Framework\SCore.cs:line 1805

Here is my log link https://smapi.io/log/d42b4b0003014e37a1992197feb504cd?Mods=game%7EModularGameplayOverhaul

**Comment by daleao** [comment]
Repeat of [Mod crash 3.1.2](https://github.com/daleao/modular-overhaul/issues/12).
