### ISSUE TITLE
CAnnot advance Forge quest

### ISSUE THREAD

**Issue by DrBretto** [daleao/modular-overhaul#2]
I speak to Clint several days after giving him the blueprints. I speak to him and the game crashes. It is getting a nullPointer exception in a loop. If I edit the save file to make the quest "complete" I can see Clint's text, but it does not add the next quest to the log. If I use the cmbt advance_quest Forge command, I get the same crash as if I spoke to Clint. It's not finding the next quest.

**Comment by daleao** [comment]
The "next quest" was removed a while back, leaving this ghost reference in some people's saves.
If you know how to edit your save I would suggest you to remove the quest entirely, and use the adv command to restart and complete it. This should make sure you get the required mail flag at the end to trigger the Forge option.

**Comment by MajorMich** [comment]
I'm also having a bit of issues with this mod, I deleted the quest from my save, which got rid of the quest, and doing cmbt adv forge restarts it but I still crash when I advance it again. 

Am I doing something wrong? Perhaps I didn't remove everything, I removed both "A dwarven Legacy" quests from my save, should I have removed "Has Dwarf Blueprint"?

 Is there another way to unlock Clint's forge without doing this quest? 

If not I really love the mod already so ill just remove the quest and hope not to trigger it, idk if that be an issue cause this is a multiplayer farm (im the host).
Please let me know if there's something I can do! Thank you!

**Comment by daleao** [comment]
I added a new file ModularOverhaul-DwarvenLegacyFix to the releases tab.
Use that version to speak with Clint and complete the quest.
After saving your game you can switch back to the standard version if you want.
