### ISSUE TITLE
Tax Evasion!

### ISSUE THREAD

**Issue by AlexTholen314** [daleao/modular-overhaul#23]
Issue: If you have an outstanding debt to the government, and they confiscate your gold from shipping things, if you save and quit the money comes back [and probably doesn't count towards your debt, didn't test]. (Sorry anybody abusing this if this gets fixed)

How to reproduce:
Step 1: Ship things (I created a new save file [with only MARGO, SpaceCore, CJB cheat, and CJB item spawner as mods] and shipped 63 banana wine iirc)
Step 2: Spend all that new money (I spent it all on sugar to ensure that it wouldn't be tax-deductable)
Step 3: Wait until the new month (I used CJB to not have to sleep that much)
Step 4: Note your new debt! 
Step 5: Ship something (I shipped one iridium bar)
Step 6: Notice the popup informing you the money has been taken
Step 7: Save and quit, and load back in
Step 8: Notice both that your money is back, and that the email in the collections log has forgotten how much you owe.

https://smapi.io/log/8c093b12bd7c40f6b6da875b26870675 is the smapi log of when I did it, and I can provide screenshots / save files if requested but with how simple it is to reproduce I figure that they are unnecessary.

**Comment by daleao** [comment]
Thanks for the step-by-step. Issue has been identified and corrected.
