### ISSUE TITLE
Savage Ring with sword combo

### ISSUE THREAD

**Issue by Fiize46** [daleao/modular-overhaul#24]
Issue : Savage Ring have bug where after you slay a monster and buff applied (+2 speed for 3 seconds) and using sword combo the animation got slowed down for a second. I also tested it on new save file and it problem also appears. 

Step
1. use Savage Ring
2. Kill a monster
3. immediately use sword combo (held down left mouse button)
4. the animation got slowed down

smapi log https://smapi.io/log/0d6e619710624c879e7e977589a5a925 

i also record what happen https://youtu.be/d7XkLlxEBxk (sorry for bad quality)

Stardew Valley 1.5.6 , Modular Overhaul version 3.1.3

**Comment by daleao** [comment]
Fixed in 3.1.4.
