### ISSUE TITLE
New download, error mod not loading

### ISSUE THREAD

**Issue by BlazeusCenturi** [daleao/modular-overhaul#25]
Sorry, didn't mean to post so fast, hit enter rather than delete waiting for smapi to load the error code

**Comment by BlazeusCenturi** [comment]
[SMAPI] Found 4 mods with warnings:
[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.

[SMAPI]       - Modular Gameplay Overhaul 3.1.3-Debug because its DLL 'DaLion.Overhaul.dll' doesn't exist.

mods in the folder atm:
GenericModConfigMenu
JsonAssets
modular-overhaul-main
customOreNodes

**Comment by daleao** [comment]
You downloaded the source code instead of the compiled mod.
Go back to the [releases](https://github.com/daleao/modular-overhaul/releases) page and read the instructions.
