### ISSUE TITLE
Crash regarding Dwarven Blueprint

### ISSUE THREAD

**Issue by UzuKirie** [daleao/modular-overhaul#26]
After waiting sufficient time with Clint for the Dwarven weapons blueprints, when I speak to him, the sound of the dialogue popping up and the quest complete chime triggers, but nothing pops up and the game crashes. This is my first time submitting any kind of issue so I'm not sure what to provide.

If I were to guess, it may be related to me having a second blueprint already when speaking to him?

**Comment by Fiize46** [comment]
I also encounter this crash where after you talk to Clint, in my case i found another three more dwarven blueprints

Step
1. Found Dwarven Blueprint
2. go to Blacksmith.
3. cutscene
4. wait several days (acquired another blueprint (idk if this the cause of crash)
5. Talk to Clint (sfx plays)
6. The game Crashed

smapi crash log https://smapi.io/log/848f0c7439ed45e2a4c73abff06841d1

Stardew Valley 1.5.6, Modular Overhaul 3.1.3
