### ISSUE TITLE
Crash on talking to Clint in Dwarven Legacy quest

### ISSUE THREAD

**Issue by GotLag** [daleao/modular-overhaul#27]
After the quest updates to say Clint has translated the blueprint, talking to him (in his shop or outside) crashes the game after playing the quest complete sound.
(`world_settime` command was used to get Clint to leave his store without waiting IRL minutes to confirm it still crashes)

Link to crash log:
https://smapi.io/log/4358b2da0224417194eb4185d65378e5

**Comment by fionabiber** [comment]
Look at the Releases Page, among the Assets for 3.1.1 theres a Dwarven Legacy Fix File for this Bug. Use that version of MARGO to get past the dialogue with Clint, save the game and then you can go back to your previous MARGO file

**Comment by SnazzySalamander** [comment]
hey I tried the fix version which worked in preventing the crash but I didn't appear to receive anything from clint even though he makes a comment about crafting the weapon if you bring the materials and giving me the "book" back. I am a little confused was I supposed to get something or a follow up quest? or is it just busted and I should just finish it with the fix version and pretend like there never was a quest so I can at least talk to clint?

**Comment by daleao** [comment]
You should now see a "Forge" option when you talk to him over the counter.

**Comment by KitsuneKinomi** [comment]
I am still getting this bug on 3.1.4, not sure if the patch was applied to later versions or not. I had started the quest in 3.1.3.

**Comment by daleao** [comment]
Maybe consider reading the text in the [release page](https://github.com/daleao/modular-overhaul/releases/tag/3.1.4)?

**Comment by KitsuneKinomi** [comment]
derp, my bad!

**Comment by daleao** [comment]
Added to main file.
