### ISSUE TITLE
"A heros Journey" Quest isnt tracking slain monsters

### ISSUE THREAD

**Issue by ArborianRoots** [daleao/modular-overhaul#29]
![20230923191837_1](https://github.com/daleao/modular-overhaul/assets/145880056/2f6aed60-d4cf-446d-b092-c9ede8c88007)
I had to set the difficulty to easy because of setting the versions of the mod in order to fix the clint crash issue making the quest reset and giving me less options to achieve each point in honor, wisdom, and compassion.
Now the quest doesnt track ANY slain monsters.
This wouldnt be an issue if it wasnt for the fact it means I could never un-curse the blade.

**Comment by daleao** [comment]
1. There are console commands to fix nearly anything. In your case, `cmbt adv honor`, `cmbt adv wisdom`, etc.
2. Assuming you're on the latest version, the quest is [no longer based on slain monsters](https://github.com/daleao/modular-overhaul/blob/main/CHANGELOG.md#patch-302-highlights--back-to-top).

**Comment by ArborianRoots** [comment]
im on 3.1.3
You can see its there though. 
Is it a bug?

**Comment by daleao** [comment]
Did you read what I linked?
