### ISSUE TITLE
Garnet nodes replace rocks

### ISSUE THREAD

**Issue by Bunlord** [daleao/modular-overhaul#3]
After I updating to MARGO to 3.1.0 version and Custom Ore Nodes to 2.3.4 I notice that all the rocks (stone nodes) in level 80 and above mine and skull cavern have been replaced by garnet nodes. Everything is loaded fine in SMAPI and I also removed the old garnet node folder. I don't know if this is Json shuffling or not. 
![Leon_9-12-2023_27540332](https://github.com/daleao/modular-overhaul/assets/144776691/e131f138-f127-428d-aa5f-79e4aecf3357)

**Comment by daleao** [comment]
Fixed in 3.1.1.
