### ISSUE TITLE
dwarven legacy quest crash on completion

### ISSUE THREAD

**Issue by pouya-alipour741** [daleao/modular-overhaul#30]
https://smapi.io/log/b3581222de144c73890c9ff42dd570b9

**Comment by daleao** [comment]
You failed requirement #4.
Go back and read the instructions.

**Comment by pouya-alipour741** [comment]
yeah I should have but i was too excited to read through all the modules, I forgot about other stuff

keep up the good work mister and please have mercy on older computers. with combat module I lag a lot in crowded mines. I  know I can deactivate it but damn masterwork weapon forging is so cool
