### ISSUE TITLE
Forge Quest Ghost Refrence Issue

### ISSUE THREAD

**Issue by Listenorelse** [daleao/modular-overhaul#4]
Saw someone posting about this issue, here to act as a bump. I tried to delete the quest ID'd 144701 and deleted the seen events ID'd 144701 and 144703. From my understanding, this should solve the issue but the quest keeps on getting triggered even after I updated the mod to 3.1.0. I also saw mail flags being mentioned but I have no idea how to add them. Please help.

**Comment by daleao** [comment]
I mean, you could have just commented on that existing thread.
Anyway, can you please share the save folder?

**Comment by Listenorelse** [comment]
[https://www.dropbox.com/scl/fi/zgz7tsdqemffkik79uplc/Saves.zip?rlkey=cl4a67x66ozjq1fzwz1bg8ash&dl=0](url)

**Comment by daleao** [comment]
I added a new file `ModularOverhaul-DwarvenLegacyFix` to the releases tab.
Use that version to speak with Clint and complete the quest.
After saving your game you can switch back to the standard version if you want.

**Comment by Listenorelse** [comment]
Thank you!
