### ISSUE TITLE
Slingshot special skill cooling bug

### ISSUE THREAD

**Issue by d3296** [daleao/modular-overhaul#42]
Hello, dear author
I'm a gamer from China, and I'm writing to you because I noticed during my gameplay that the "Slingshot" will not cool down under certain circumstances. (After using the Slingshot special skill, switching to a different weapon or item triggers a situation where the CD cannot be cooled down.) I'm not sure if this is a conflict with other mods, if not, I'd like you to fix it.

Best wishes.

**Comment by daleao** [comment]
Fixed in 3.1.6.
