### ISSUE TITLE
Garnet nodes gives housplants and other items seem to be missing

### ISSUE THREAD

**Issue by TheDragonQueen** [daleao/modular-overhaul#44]
Hi, so as the title says, i'm not getting garnet and trying to look the items up in CJB shows nothing. After talking with some members in the Stardew Valley Discord and trying to troubleshoot it, nothing has worked and we couldn't identify the issue. I tried doing a clean install and removed a couple of mods that turned out to not necessary(Golden and Ostrich mayo), but the issue still persists. Though someone said "But from what I could tell of your SMAPI log you're being warned for parts of MARGO failing to grab what it needs to work properly." so idk if that helps narrow down what's going wrong. 

 Here's my most recent log: https://smapi.io/log/dd5e257cbd4445f8b5907da58ba7b8a5

I'm very sorry for not being able to add any other info, i just don't understand what's going on and anything modding related that isn't "click and drag files into the correct folders" goes over my head.

**Comment by daleao** [comment]
There's nothing wrong with your log.
Try to disable and re-enable the Combat module.

**Comment by TheDragonQueen** [comment]
Ok, did that and it worked! Thank you. :D

Oh, ok. Then i'll redownload them. Thank you. ^^
