### ISSUE TITLE
Not Getting Dwarven Legacy Quest

### ISSUE THREAD

**Issue by Noodleboiby** [daleao/modular-overhaul#47]
So, I picked up a dwarven blueprint and from what I read, I'm supposed to get the Dwarven legacy quest. However, after I picked it up, I got a prompt that someone who can decipher it should read it and then nothing else happens 

https://smapi.io/log/9c5361802e474752ab914d7dcb4f9bc2

I hope this helps to some degree

Also, my poor farming is bugged, I'm at level 20 but the game thinks im only at level 18

**Comment by daleao** [comment]
The quest begins after you visit said someone.
As for your farming level, if the games says you're level 18 then who are we to question it?
Type in `prfs levels` to the console to check your exp and level in each skill.
