### ISSUE TITLE
Can't get damaged with Combat Module enabled

### ISSUE THREAD

**Issue by AlanBF1992** [daleao/modular-overhaul#48]
If the Combat Module is enabled, you won't get damaged by monsters or bombs, as long as you don't hold a weapon.

Steps to reproduce

1. Enable Combat Module
2. Hold anything that's not a weapon
3. Try to get damaged by a monster

It doesn't matters if any other module is enabled, as long as the Combat one is enabled you won't get damaged.
Scythes are coded as weapons (it looks like), so you can get damaged if you hold it.

**Comment by daleao** [comment]
Fixed in 3.1.7.
