### ISSUE TITLE
config problems on steam deck

### ISSUE THREAD

**Issue by UncleLono** [daleao/modular-overhaul#5]
Hi! Love what you made.

I just want to let you know the config menu doesn't work on Steam Deck. The only way I found to do it was to plug in an actual mouse.

**Comment by daleao** [comment]
This is known issue with the multi-column options.
I never bothered to fix this, but I have now added a fallback to a controller-friendly layout when gamepad mode is detected.
You can try this out with [this](https://www.dropbox.com/scl/fi/2v126upq6n47fj4b46qm1/ModularOverhaul-3.1.2-Debug.zip?rlkey=wx98jmjvwd9h14a1b68lezc7l&dl=0) version.
