### ISSUE TITLE
Accidentally strengthened curse

### ISSUE THREAD

**Issue by tjdwo13579** [daleao/modular-overhaul#50]
I accidentally strengthened curse by the console command "cmbt curse"
2 times. 

Now it's draining a third of my health with one swing.
Is there a way to weaken it by console?
I know bless removes it completely but I want to go through the quest normally.

I strongly suggest some kind of official guide for the curse.
I think the quest is fun but sometimes too confusing.

**Comment by daleao** [comment]
>I accidentally strengthened curse by the console command "cmbt curse"
Every command is documented if you provide the parameter `help`. E.g., `cmbt curse help`.
Never run commands before understanding what they do.

>Is there a way to weaken it by console?
Just give the command a number; e.g., `cmbt curse 50` will set it back to the basic level at which the quest begins.
