### ISSUE TITLE
Causes Better Chests to crash

### ISSUE THREAD

**Issue by mj717** [daleao/modular-overhaul#51]
I can't use the latest version of this mod with Better Chests. Better Chests is now unable to open/is crashing when I try to view my chests. Based on the error message I'm getting, it seems like it's this mod (Tools Module) that is conflicting with Better Chests in some way.

SMAPI: https://smapi.io/log/420244d4a083411abbd1b4789928b509

**Comment by daleao** [comment]
Should be fixed in 3.1.8.
