### ISSUE TITLE
Unclear how to throw ingots into radioactive fish pond

### ISSUE THREAD

**Issue by Pachtjuilaard** [daleao/modular-overhaul#56]
I've tried throwing ingots and ores, (copper, iron, gold and iridium) into the pond, tried interacting with it as well. Nothing seems to work. I've tried with one Radioactive Carp in the pond. Does the pond need to be completely full before something can be thrown in?

**Comment by daleao** [comment]
Not full but the pond needs to have changed color, which requires 2 or 3 iirc.

**Comment by PurpleManiac** [comment]
> Not full but the pond needs to have changed color, which requires 2 or 3 iirc.

But how does this necessarily work? Who are radioactive bars for? Is this for use with the dwarven tool quests or is it an addon to work with another mod?

**Comment by daleao** [comment]
What do you mean "what are they for"?
They're Radioactive Bars/Ore, to be used wherever you need Radioactive Bars/Ore.
