### ISSUE TITLE
Golden eggs

### ISSUE THREAD

**Issue by PigeonX018** [daleao/modular-overhaul#57]
Golden eggs can only produce one mayonnaise after installing modular overhaul. (Note: silver-quality mayonnaise can be produced) After uninstalling this mod, golden eggs can produce three. Not sure whether the bug is caused by Artisan (the skill at level 10 of farming), but it is sure that the bug is caused by this mod rather than the mod conflict with the others.

**Comment by daleao** [comment]
Not a bug. It's caused by Quantity Over Quality setting from Tweex. Golden eggs produce 1 mayo at gold quality or better.
