### ISSUE TITLE
Infinity Slingshot error

### ISSUE THREAD

**Issue by congha22** [daleao/modular-overhaul#58]
https://smapi.io/log/2f73838d9975443a9fc78858a5ec3405

Get infinity slingshot with CJB cheat, error show whenever use it. Cannot open inventory, but can open CJB cheat menu. After warping to another location, can open inventory. Then if move the slingshot to another slot, error remove

**Comment by daleao** [comment]
CJB Cheats Menu just cannot spawn custom slingshots. Nothing I can do. You must obtain it legally.
