### ISSUE TITLE
After 3.0.1, can't make it work

### ISSUE THREAD

**Issue by Usolia** [daleao/modular-overhaul#59]
Hello. I wanted to use an update version or MAGO.

I have the last version uploaded on nexus i think, the 3.0.1. It work pretty fine (even if i have a bug with monsters), but, when i download the last version, NOTHING work.

I use Stardrop to launch my games, i SAW the mod in my active mod list, but when i start, nothing. It's looks like he's not in the game.

I try other version too, but the only one who work right now it's the old one.

Any idea?

**Comment by daleao** [comment]
Would help if you attached your SMAPI log.
But off the top of my head I'm gonna guess you downloaded the wrong file.

**Comment by Usolia** [comment]
My bad. When i log the smapi, i found an error. It's totally my fault, didn't see it sooner (even if i checked T^T)

Sorry for the bottering! Good job with this mod, it's really give a nice touch to the game!
