### ISSUE TITLE
Weapon obtain before installing mod have problem

### ISSUE THREAD

**Issue by congha22** [daleao/modular-overhaul#60]
Weapon that in inventory before install mod have different stat like bone sword, club, ...

**Comment by daleao** [comment]
I don't understand what the problem is.

**Comment by scottysimply** [comment]
@daleao:
> I don't understand what the problem is. If you need help please consider giving a detailed description of the issue. Describe what is happening and what you expected should happen instead. Include screenshots, specific details. It's unreasonable for you to expect any help from just "stats are different".

I believe they are referring to the fact that if you enable [CMBT](Modules/Combat), or really any module mid-playthrough, it causes a JSON shuffle. It may be a good idea to put a line in the readme that tells players to not to enable modules mid-playthrough. This of course, assumes that people actually read it :p

As for @congha22, there is a bolded text _on the readme_ under [CMBT}(Modules/Combat) that says: "This module adds new items via Json Assets, and thus may cause Json Shuffle on existing saves." To explain it simply: assets are stored on JSON files. When these are parsed into the code, they are completely unordered. Adding or removing assets can and most likely _will_ cause a desync. Note for the future: if you're using git, read the readme!

**Comment by daleao** [comment]
I don't think they're talking about JSON Shuffle. I think they just enabled the Combat module and didn't realize it would change weapon stats.
Please just read the mod description.
