### ISSUE TITLE
Tool Range Not Working

### ISSUE THREAD

**Issue by andip23** [daleao/modular-overhaul#61]
Edit: my Golden Scythe used to have a very wide range, but appears to have also reverted to vanilla range for some reason. My Lava Katana doesn't look cool and fiery anymore, and the Blade of Ruin has changed appearance. I guess I'll go back to the version I had before for now.

I've never been able to get the tool range to increase with each upgrade level like it says they will. I just downloaded the latest version of MARGO and I see this in yellow in my SMAPI log:
[Modular Gameplay Overhaul] [TOLS]: Too many values in Axe.RadiusAtEachPowerLevel. The default values will be restored.
[Modular Gameplay Overhaul] [TOLS]: Too many values Pickaxe.RadiusAtEachPowerLevel. The default values will be restored.
[Modular Gameplay Overhaul] [TOLS]: Too many values in Hoe.AffectedTilesAtEachPowerLevel. The default values will be restored.
[Modular Gameplay Overhaul] [TOLS]: Too many values in Can.AffectedTilesAtEachPowerLevel. The default values will be restored.

How can I resolve this? I'd love to see how the tools work with this feature enabled.

**Comment by scottysimply** [comment]
Preliminary question: Did you enable/disable a module or (un)install another mod mid-playthrough? This can cause a JSON shuffle, where your items gain or lose attributes you should not have. Rule of thumb: Make a new playthrough when you are adding or removing JSON content mods, or altering the configuration of one.

**Comment by daleao** [comment]
1. You obviously disabled the Combat module. Maybe check if it's enabled before reporting it as not working.

2. You need to hold the shift key, unless you configured it otherwise.

**Comment by andip23** [comment]
No need to be rude. I’m new to this.On Oct 14, 2023, at 2:58 PM, daleao ***@***.***> wrote:﻿


You obviously disabled the Combat module. Maybe check if it's enabled before reporting it as not working.


You need to hold the shift key, unless you configured it otherwise.
