### ISSUE TITLE
Stolen and uploaded onto NexusMods

### ISSUE THREAD

**Issue by Pixl64** [daleao/modular-overhaul#64]
Not sure if this is the right place to post about this, but I think someone reuploaded this mod to NexusMods. They appear to have directly copied the description, as the images don't work correctly, and neither do the links explaining the modules.

https://www.nexusmods.com/stardewvalley/mods/18760?tab=description

**Comment by PurpleManiac** [comment]
I saw that too! I already sent a message to the author asking if he had authorization, I included it to ask for donations...

People's nerves are impressive...

**Comment by Fluffefle** [comment]
Yeah, they even disabled comments... people can be so dumb.
