### ISSUE TITLE
Can't obtain cursed sword quest.

### ISSUE THREAD

**Issue by ooglopboy** [daleao/modular-overhaul#66]
So I was able to get in to the quarry mine, got the cursed sword, got to talk to the wizard about how dangerous the sword is, killed the 50 enemies with it, and now just... nothing. The altar of Yoba doesn't tell me about the trials. I'm just stuck with a sword that is slowly killing me lol. Is there some command I can input to START the quest? I tried the "ars advance_quest Ruin" but that didn't do anything.

**Comment by PurpleManiac** [comment]
**Try talking to Gil in the adventurers' guide, this will help him start the quest.**

**Comment by daleao** [comment]
Seems like you got some things backward:
1. After first obtaining the sword, you need to defeat 50 enemies with it in order to trigger a letter from the Wizard.
2. Only after you read said letter, a cutscene should trigger when you visit the Wizard.
3. After the cutscene, the quest immediately starts.

Please review which of the events above failed to occur.

**Comment by ooglopboy** [comment]
Ive had all of them. the sword is currently up to over 200 base damage so Ive killed WELL over 50 enemies with it and I have already had the meeting with the wizard. As of now I have also talked to Gil and had him tell me about the "tenets of yoba" or however he put it and the altar still does not give me any of the dialogues.

**Comment by ooglopboy** [comment]
Just to be safe, today I talked to Gil, went down in to the mines and killed another 50 enemies, checked my collections tab to see that I DO have the Ruined Hero letter and know I've already had the cutscene, went to the wizards tower to see if any new scenes occurred, and then checked the Yoba altar. Nothing.

**Comment by daleao** [comment]
Do you have the quest but the statue is not working, or did you not receive a quest at all?
Please include a link to your save folder in your response.

**Comment by ooglopboy** [comment]
I didnt receive the quest at all. When I talk to the altar it just tells me something along the lines of "evil can not touch a hero of Yoba." The weirdest part is this is my second save file with this mod pack and it worked fine the first time after I moved the "magic mod" altar location so they didnt overlap. This time its just... not? as for the save file, sorry, Im not sure how to go about including the link?

**Comment by daleao** [comment]
Paste this in your file explorer: `%AppData%\StardewValley\Saves`
Zip up the folder with your farmer's name on it.
![image](https://github.com/daleao/modular-overhaul/assets/111105627/b5a2fca4-3633-46d1-8bfd-bdf22b677406)

Then upload it to Google Drive, Dropbox or anything like that and share a link here.

**Comment by ooglopboy** [comment]
https://drive.google.com/file/d/1S9UJ50OU8PH3zJEuiLTkX8jEMPUHgJah/view?usp=share_link

**Comment by daleao** [comment]
So you said you had all 3 steps that I mentioned above, but you do not actually have number 3.
Although you did receive the mail, and did see the event, the quest, for whatever reason, was not started, so obviously the Altar was not responding.
If you have Event Repeater, you can trigger the event again using `debug ebi 144703`.
Or you can type `cmbt adv curse` to force start the quest.
Then just proceed as normal.
