### ISSUE TITLE
The mod causes the Ginger Island animation to drop frames

### ISSUE THREAD

**Issue by d3296** [daleao/modular-overhaul#69]
Hello author, this is also a new bug I found during playing: after loading your mod, the Ginger Island action animation will freeze. I'm not sure if it's a conflict with other mods, if it's not your problem I can compare my current mods one by one by elimination

**Comment by daleao** [comment]
What do you mean by "Ginger Island action animation"?
Can you please provide step-by-step instructions to reproduce the issue?

**Comment by d3296** [comment]
Simply put, I now drop frames when I'm active in the Ginger Island Farm area

Uploading 屏幕录制 2023-10-20 221926.mp4…

![屏幕截图 2023-10-20 221158](https://github.com/daleao/modular-overhaul/assets/146864487/01084e84-f50b-4981-b45f-ce8b0b9efd4e)

**Comment by daleao** [comment]
Please read the [reporting instructions](https://github.com/daleao/modular-overhaul#reporting-bugs-or-issues) and upload your whole log and not just a screenshot.

**Comment by d3296** [comment]
[SMAPI 3.18.6 - running Stardew Valley 1.5.6 with 38 mods.txt](https://github.com/daleao/modular-overhaul/files/13059691/SMAPI.3.18.6.-.running.Stardew.Valley.1.5.6.with.38.mods.txt)

**Comment by daleao** [comment]
You obviously did not read the instructions as I asked.

**Comment by d3296** [comment]
Thank you for your patience, here is the link to the log report hope it will be helpful to you.[https://smapi.io/log/2f8b3ac1d9944e30b08c00be0d11db6e](url)

**Comment by daleao** [comment]
Thank you for the log. But can you please describe exactly how to reproduce the issue in steps?

**Comment by d3296** [comment]
Sorry, I've tried a lot of ways to figure out what the problem is, like opening a new save or changing the farm, but unfortunately the error still keeps going no matter what I do.

**Comment by d3296** [comment]
I also tried reloading the game or reinstalling mods, but to no avail.

**Comment by d3296** [comment]
The SMAPI version is：“3.18.6”
The game version is：“1.5.6”

**Comment by daleao** [comment]
That's fine. I'm not asking you to find the cause of the problem.
What I need is for you to tell me what you are doing in the game in order to trigger the issue.
Tell me exactly what to do so I can trigger the issue on my side, and then I can use that to find the problem.
For example:
1. Start new save.
2. Go to XXX location.
3. Do YYY.
Etc...

**Comment by d3296** [comment]
No matter what I did before, a bug will appear now when I am on Ginger Island Farm. I'm sorry that I can't provide you with more useful information. I think it may be the problem with my equipment.

**Comment by d3296** [comment]
I found the reason. The bug was caused by the tiger slime on Ginger Island Farm. After I killed the slime in the upper left corner of the farm, the bug disappeared.

**Comment by d3296** [comment]
This bug is not limited to Ginger Island Farm, but also appears in mines, skeleton mines, and volcanoes.

**Comment by daleao** [comment]
Monsters are a feature of the game. They cannot be themselves the cause of a bug.
If your solution is to "clear all monsters", then that is obviously not a good solution.

Will you please provide instructions to repeat the issue?
Is it just "warp to Ginger Island Farm" and that's it? Or does it happen when you fight a monster? When you kill a monster When you use a specific skill or profession? A specific weapon?
Can you share your combat level and combat professions?
Please share these details so I can try to find a fix.
I just need to know exactly how to repeat this on my own game.

**Comment by d3296** [comment]
There may be a problem with my computer, because currently the bug is triggered whenever a monster appears in the map. I'm sorry that I can't provide you with more useful information. Maybe this bug won't appear after the game is updated to version 1.6. Thank you for your efforts :)
