### ISSUE TITLE
Possible incompitabilty with "Better Crafting" with update.

### ISSUE THREAD

**Issue by Ange1icAura** [daleao/modular-overhaul#7]
Hi,

I can no longer craft rings that require other rings, for example "Glow Ring", when I have "Better Crafting" installed. This was working prior but I'm not sure what version of your mod stopped being compatible. Tried on a new save and the issue persisted.

https://github.com/daleao/modular-overhaul/assets/71840098/a1090dc2-07ab-4765-b4c9-259cb139a6ca

Log: https://smapi.io/log/04f7142673ba4c82ae4a0bd9939cc852

Better Crafting: https://www.nexusmods.com/stardewvalley/mods/11115

**Comment by daleao** [comment]
Thanks for reporting.
Fixed in dev build.
