### ISSUE TITLE
Question about the legacy changelogs

### ISSUE THREAD

**Issue by cho0pera** [daleao/modular-overhaul#70]
Hi, I just noticed this section below the regular changelog for modules that have been merged and no longer exist. 

Not sure when these changes happened but I usually look over the changelogs whenever there's an update. It's a little tricky to keep up with GH cuz I'm not as familiar with it. 

Mostly interested in the Enchantments and Rings modules - do they exist? what have they been merged into if so? 
Or if you could point me to where these changes are explained that'd be appreciated too. Thanks!

**Comment by daleao** [comment]
They are both part of [Combat](https://github.com/daleao/modular-overhaul/tree/main/Modules/Combat) module. The merge itself is listed in the changelog of [Combat](github.com/daleao/modular-overhaul/blob/main/Modules/Combat/CHANGELOG.md#300).
