### ISSUE TITLE
Skill Selection Screen crash after Qi D. skull cavern run

### ISSUE THREAD

**Issue by tytanitex** [daleao/modular-overhaul#71]
Was doing hard skull caverns Qi quest and the game crashed when i got to the choose a new fighting profession screen at night. Failed to save. I didnt try to reproduce it yet
https://smapi.io/log/540437bc9655444c9a7db8c63f637d69
EDIT: did not reproduce when i attempted it again

**Comment by daleao** [comment]
Neither are there any errors in the log, so I guess there's nothing else to do for now.
