### ISSUE TITLE
Issues with new update

### ISSUE THREAD

**Issue by prothico** [daleao/modular-overhaul#72]
There are two issues that I encountered today. When you open the player menu to the professions tab, the skills don't have the stars next to the level or colors next to them anymore and show older text descriptions. 

To recreate:
Press E to open player menu
Click on professions tab.

Also, when entering the golden scythe area next to the quarry, I lose the ability to perform any ingame actions. I could open menues but I couldn't swap items in hand or use anything. I was holding galaxy sword when the game froze. When I got to the cave I was getting attacked by a brown slime and tried to click with mouse to attack and nothing happened. I do not remember if I entered the cave holding sword or if I was able to switch to it once I got there. Once I realized I was gonna die I used CJB to teleport back to farm. The issue persisted once I teleported. I couldn't change items or interact with the map using directional keys or clicking with mouse.

To recreate:
CJB teleport to quarry
walk to flying skulls cave using directional keys
once in the cave try to swing galaxy sword

**Comment by daleao** [comment]
You forgot to include a log.
I suspect your Margo isn't even loading.

**Comment by prothico** [comment]
Fixed. When updating you need to Shift+F12 and reselect the modules.
