### ISSUE TITLE
Hanging overnight on skill up?

### ISSUE THREAD

**Issue by ooglopboy** [daleao/modular-overhaul#74]
Not to sure what to label this as, sorry. I only figured I should look for help here because I see the MARGO mod as the last thing in red on the SMAPI Window.

Issue: Going to bed and getting the level up noise, then I just hang on a black screen without getting to the "saving game" notification.

What I've done:
-Leave the house and send a Prismatic shard to whoever's birthday it is
-pick and replant all the ready plants on my farm
-go to ridgeside and get a few cutscenes
-fix the ridgeside minecart
-go home for the night and place all of my farm goods in their respective chests
-go to bed
-hear the level up sound, screen stays hanging on black.
https://smapi.io/log/9af2fcd881834b81aaea4c2a4afea226

**Comment by ooglopboy** [comment]
ok I just did a little testing and it looks like its the Magic Skill added by the Magic Mod?

**Comment by daleao** [comment]
You are using an extremely old version of Margo. The latest version is 4.0.0 and you are using 1.0.1. You should update your mods first of all.

**Comment by daleao** [comment]
I'll assume this is resolved.
