### ISSUE TITLE
Lifting the curse

### ISSUE THREAD

**Issue by andip23** [daleao/modular-overhaul#77]
Hello! I have a question about the ruined blade quest. I have already completed all of the steps necessary to prove my virtues, but I did not know I had to visit the shrine of Yoba to get directions, so I've just been winging it. Now that I've visited the shrine, the quest in my journal tells me I've completed all the necessary tasks, but the completion bars are red rather than green. (They say 1/1 but are still green because I went out of order.) I have 10 hearts with everyone and have no more cutscenes wherein I could be compassionate or wise again to make the bars green, though when I gave someone a gift it did register that I'd proven my generosity. Is there a way I can make or mark the quest completed given that I'm already this far in the game? (I'm only in year 2 but I mean regarding cutscenes all being completed.) Thanks!!

**Comment by daleao** [comment]
Type in the console `cmbt adv curse`.
Will try to fix this for next update.
