### ISSUE TITLE
Error regarding config.json "Mod crashed on entry and might not work correctly"

### ISSUE THREAD

**Issue by lvbit** [daleao/modular-overhaul#84]
Updated to latest version (4.1.0) and as always kept my config.json
I have all modules activated except for taxes.

When starting the game I get  "Mod crashed on entry and might not work correctly" error. The game starts, but I do not see an entry in the Generic Mod Config Menu for Modular Gameplay Overhaul.

link to config file:
https://c.web.de/@319391227306841863/jsZ3PhnqTbSqe0NTDYitpw

link to log:
https://smapi.io/log/1e161f2ce883492b8cb2c2d232e58948?Mods=ModularGameplayOverhaul

Tried with all other mod deactivated, except for "SpaceCore", "Error Handler" and "Generic Mod Config Menu", but same thing.

link to second log:
https://smapi.io/log/9b8806bea2454ba8a3ff0be4683ff077?Mods=ModularGameplayOverhaul

What helps is deleting the old config.json file. However I would like to have a way to keep the settings.

**Comment by daleao** [comment]
If you pay attention to the log error you can see exactly what's causing the issue.
I highlighted it here for you:
![image](https://github.com/daleao/modular-overhaul/assets/111105627/108e02a7-8262-492d-b4f3-6916a0545069)

Open your config, search for that setting and delete it. SMAPI will regenerate only the missing configs.
If you get another error just repeat this until it works.

**Comment by lvbit** [comment]
It worked. Thank you for the quick help. And also thank you a lot for creating and sharing this incredible mod.
