### ISSUE TITLE
4.10 Skill issues

### ISSUE THREAD

**Issue by ziat007** [daleao/modular-overhaul#85]
When upgrading to 4.10 from 4.0.1 I get a lot of red errors with socialising and binning. After downgrading back to 4.0.1 these issues were gone.

**Comment by ziat007** [comment]
It does seem to be MGPO causing this error.
https://smapi.io/log/dbf18bbd66fa4da1a6239c067fb318be

**Comment by daleao** [comment]
Something may have changed in this mod that broke the other mod's compatibility.
It's up the other author to update their compatibility.

**Comment by ziat007** [comment]
turned out to be an MGPO config issue.
