### ISSUE TITLE
Updating from 4.0.1 to 4.1.0 turns my infinity gavel from a club into a sword

### ISSUE THREAD

**Issue by Kelenius** [daleao/modular-overhaul#86]
The picture, name, and the stats all stay the same, it just turns into a sword and gets the sword special move. I'm only using Professions and Ponds modules.

**Comment by daleao** [comment]
If you are not using and had not been using the Combat module then there is no way updating this mod could cause any change with your weapons. Can you confirm that by simply rolling back the update your gavel behaves correctly again?

Easiest way to fix your issue would be to simply trash the weapon and spawn a new one with Item Spawner.

**Comment by Kelenius** [comment]
Yes, when I use 4.0.1 and load my save it's a club, and if I update to 4.1.0 and load the same save, it turns into a sword. I'm not using and have never used Combat.

**Comment by daleao** [comment]
In that case, can you please share the save folder ?

**Comment by Kelenius** [comment]
[Victor_261174921.zip](https://github.com/daleao/modular-overhaul/files/13227731/Victor_261174921.zip)

I'm using other mods, but the only one that interacts with weapons is ManyEnchantments, which shouldn't cause this, and I checked that the save loads with just SMAPI + SpaceCore + MGO, and the change still happens when switching versions.

**Comment by daleao** [comment]
I loaded your save with 4.1.0 and the gavel in your backpack swings and behaves like a club.

**Comment by daleao** [comment]
Indeed my fault. Thank you for the report.
Should be fixed in 4.1.1.
