### ISSUE TITLE
Sprite freezes and farmer becomes unresponsive after attacking with dragontooth cutlass

### ISSUE THREAD

**Issue by philredman** [daleao/modular-overhaul#87]
Setup: 
- version 4.1.1
- Professions, Tweex, and Ponds modules enabled. Combat is NOT enabled. Limit break is disabled.
- weapon: dragontooth cutlass, in slot 1

Issue:
- When I attack with the cutlass, my farmer's sprite freezes mid-animation. 
- At one point, I was able to attack a few times upon waking up in the farm house, but by the time I got to the Secret Woods, I was freezing again
- Sprite seems to freeze on the first frame of the animation - so if the farmer is facing left, the cutlass will be stuck like it's being "held" vertically above the farmer's head
- This makes me lose the ability to control the farmer: I cannot move, cannot attack, cannot switch item slots, cannot open my inventory (bound to Tab for me), or anything else. 
- I can, however, open the CJB Item Spawner menu and move my tools around, which then lets me open my inventory, and rearranging my tools enables me to start moving around / using tools / etc. 
- There's no error that appears in SMAPI (just the green slime wall of text error)

SMAPI log:
https://smapi.io/log/f4b9bfaea80e4e34a240e9049dab67c1

I'll see if this behavior repeats with other weapons.

**Comment by philredman** [comment]
Alright, testing with the yeti tooth, trident dagger, dragontooth hammer, wooden hammer, and galaxy sword, in addition to the original cutlass, it looks like this isn't reproducing. 

Maybe it was something to do with setting stuff up in the config after I'd updated to 4.1.1? Not sure, but it reproduced a few times after restarting the game originally, and now it doesn't. Problem solved for now, I guess. I'll let you know if I get this behavior again.

Overall though, thanks for this mod! Lots of good stuff here, I appreciate it.

**Comment by daleao** [comment]
This usually happens when you have a Stabbing Sword and disable the Combat module.
The game doesn't know what to do with a Stabbing Sword since it only expects Defense-type swords.
But if you never had Combat enabled at all then idk why this would be the case.

By enabling Combat module and turning off Stabbing Swords (while in-game) you should fix this.
