### ISSUE TITLE
Infinity Dagger now has the stats of the Galaxy Dagger

### ISSUE THREAD

**Issue by Veginite** [daleao/modular-overhaul#89]
I updated the mod to the latest version a few hours ago. Pretty sure this triggered when reloading the game. It was level 10 when I made it.

![image](https://github.com/daleao/modular-overhaul/assets/78785511/4c898e7f-7468-4078-b593-0f783b5b3a2c)

**Comment by Veginite** [comment]
Upon adding a gemstone, the dagger's level increased to level 7. Nothing else happened with the subsequent three gemstones.

Upon enchanting it, the crit chance from two of the aquamarines no longer displays on the tooltip and I'm not sure if I have it. The bonus from the two garnets is still showing.

![image](https://github.com/daleao/modular-overhaul/assets/78785511/e5c8cbdb-9cc2-4752-b55b-617b4701ee6b)

**Comment by daleao** [comment]
Those stats don't look like Galaxy Sword either. Idk what happened. Try entering the command `cmbt refresh` with it selected.

**Comment by Veginite** [comment]
Okay! Ran the command and the crit chance is now back. It does however disappear rather quickly if I change areas or reload the game.

**Comment by daleao** [comment]
Issue should be fixed in 4.1.2.
You may need to run the command `cmbt refresh` one more time.
