### ISSUE TITLE
Sword becomes level 1

### ISSUE THREAD

**Issue by cho0pera** [daleao/modular-overhaul#91]
Hello, I'm not sure if this is a bug or user error regarding config settings but I've found that my farmer's sword gets lowered to a level 1 sword when it's in my inventory. I used CJB Item Spawner to replace it and then it seems to show the correct level and function at that level, but until then it will show up as a level 1 sword and have very weak fighting power. This happened with two different level 6 swords (Lava Katana and another one I can't recall the name of). I think this happened on 4.0.1 and currently on 4.1.0 /4.1.1.

Am I missing something? Like some part of the config for CMBT that might do this perhaps? I've been trying to read through the modules overview - it's A Lot to process. Appreciate your help! 

[config.json](https://github.com/daleao/modular-overhaul/files/13242311/config.json)

Here's my latest [log](https://smapi.io/log/3ceda388406948479a2f4ace3a764533) (ignore the big error with CJB Cheats, I messed up when editing the warps.json)

**Comment by daleao** [comment]
Can you share the save?

**Comment by cho0pera** [comment]
Here's my [save file](https://drive.google.com/drive/folders/16bht8_zkSiEdcDF5EXHCpXEfbvGJpHRo?usp=sharing). 
(Think I did that right, LMK otherwise)

**Comment by daleao** [comment]
Version 4.1.2 should fix weird weapon stat resetting.
You may need to run `cmbt refresh` on the specific weapons that were affected (select them in the hotbar before running the command for each one).
If this happens again afterwards please let me know.
