### ISSUE TITLE
issues with loading the config

### ISSUE THREAD

**Issue by nahyutarightsactivist** [daleao/modular-overhaul#93]
the mod is unable to parse the config when reloading the game. the mod functions perfectly when i generate a new config with every launch, but i would quite like to avoid going through the rigmarole. 

i believe that setting the galaxy sword to be a stabbing sword using GMCM may be causing issues, and i would be willing to test that if it would be helpful.

this is a log with all 405 mods i use:
[https://smapi.io/log/c4782d332d9749678bd75bed8b5351e7](url)
some of these mods have a few issues, like bad update keys and redundancies, but i don't believe they interact negatively with margo.

this is a log with only margo and dependencies:
[https://smapi.io/log/1ec4aed4b03e4ec8a3333dae02c298e2](url)
the issue occurs identically in this case.

thank you for the time, and i hope i supplied enough information!

**Comment by Erin105** [comment]
This might be because the text entry fields for ArtisanMachines, AnimalDerivedGoods, and StabbingSwords are being improperly limited to 13 characters in GMCM. This means if you save after making any changes, it truncates those entries making them now malformed. 

Can workaround by editing the config.json directly without GMCM.

**Comment by daleao** [comment]
Check out what the error actually says:
![image](https://github.com/daleao/modular-overhaul/assets/111105627/2d0c64ea-fba8-438d-84b6-adb38953ca4f)

Just search for and delete that field. SMAPI will regenerate just the missing configs.

**Comment by Erin105** [comment]
> > This might be because the text entry fields for ArtisanMachines, AnimalDerivedGoods, and StabbingSwords are being improperly limited to 13 characters in GMCM.
> 
> @Erin105 are you sure about that?

Anytime I save the Professions or Combat sections, yes it does.

Might be a separate bug though.

**Comment by daleao** [comment]
Sounds like a GMCM limitation then.

**Comment by Erin105** [comment]
> Sounds like a GMCM limitation then. Not a bug.

I'm not an expert on GMCM, but not all GMCM text entry boxes limit character like this, for example, the one from the Magic mod allows far more characters, maybe a limitation of the + - boxes you are using?

**Comment by nahyutarightsactivist** [comment]
deleting the problematic line(s) (i deleted both occurances of auto tool selection) does seem to fix the issue! i have to wonder though, do you have any clue what might have made the lines problematic in the first place? it's just very odd to me that it worked like that.

**Comment by daleao** [comment]
Yes, there's a note in the download page. Several configs were changed in 4.0.0.

**Comment by nahyutarightsactivist** [comment]
okay thank you!

**Comment by daleao** [comment]
> I'm not an expert on GMCM, but not all GMCM text entry boxes limit character like this, for example, the one from the Magic mod and Timespeed allows far more characters, maybe a limitation of the + - boxes you are using?

It was indeed my fault and not GMCM. This will also be fixed in the next update.
