### ISSUE TITLE
20:34:06	ERROR	Modular Gameplay Overhaul	Mod crashed on entry and might not work correctly. Technical details:

### ISSUE THREAD

**Issue by SGamerXxX** [daleao/modular-overhaul#94]
https://smapi.io/log/97151504bfe440078828dcd68f937f7d

An odd bug that appeared when I updated to the latest version. It appears to freeze the game when I swing my Infinity Sword.

**Comment by daleao** [comment]
You just didn't notice that the mod didn't load at all, so the game doesn't know what to do with your stabbing sword.

Your config file is badly formatted. To fix, either delete and generate a new one, or open it in a text editor, search for "DeductibleExtras" and delete that field.

**Comment by SGamerXxX** [comment]
Hmm, odd. So I deleted the "DeductibleExtras" line as stated. Seems to be working now. Thanks.
However when I started up it replaced the 
`"DeductibleExtras": []`, with `"DeductibleExtras": {},`

Not sure why it broke after I updated the mod.
