### ISSUE TITLE
Impossible-to-complete Prospector Hunts?

### ISSUE THREAD

**Issue by Exaxxion** [daleao/modular-overhaul#98]
Using MARGO v4.1.2 with all modules except TXS enabled.

After multiple successful Prospector Hunt minigames, I have received two minigames in a row in which I broke every single stone in the floor of the mine and got no reward. Upon leaving the floor, I get the message "tingling has stopped" indicating that it ended in failure, rather frustratingly terminating my built up streak.

I primarily use manually-detonated (mod key held) bombs for mining per the Demolitionist tree perks. Does doing so automatically fail the minigame? Only thing I can think of is maybe the blast hit the target stone before I got close enough to it to qualify as winning. If so it's rather unfun to lose when you do break the right stone, but from too far away, particularly when you have a dense block of stones and ores in the way that would normally make the most sense to bomb for extra materials.

**Comment by Exaxxion** [comment]
As an addendum to the above, I attempted to increase the detection range with Generic Mod Config Menu to hopefully work around it, but instead every hunt that triggers instantly fails; the toast notification appears with "Your prospector senses are tingling" on loading into the mine floor, then before the screen has even fully transitioned from black it pops up "the tingling stops".
![image](https://github.com/daleao/modular-overhaul/assets/11907282/b5a4b7df-876f-48c7-9ba1-74b192a32c4b)

**Comment by daleao** [comment]
The detection range is simply the distance at which the stone is revealed to you, the player.
The hunt itself tracks all stones removed from the current location, regardless of how it happened or how far away.
I'll have to do some testing to see if I can replicate your issues.

**Comment by Exaxxion** [comment]
Makes sense to me, I'm not entirely sure what happened. I was able to play a little again today (so the game was launched fresh) and from delving into the regular mines and skull cavern both it seems to be working normally again, so maybe there's some edge case where it broke.

**Comment by daleao** [comment]
You can turn up the treasure hunt chance to 100% if you would like to do your own testing. If you come up with reproducible steps then let me know.

**Comment by Exaxxion** [comment]
I have as of yet been unable to reproduce the issue but I have noticed that completing a hunt sometimes spawns items well outside of bounds, like as pictured:
![image](https://github.com/daleao/modular-overhaul/assets/11907282/f14baa4c-19bf-4e11-8bbe-4e528b46ffa8)

It's always one or more weapons that spawns in this manner, I haven't seen regular stuff like prismatic shards do that.

**Comment by daleao** [comment]
Thanks. Fixed.
