### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by 2970194508** [daleao/modular-overhaul#99]
Is there a way for me to make it work perfectly with PFMautomate?

**Comment by 2970194508** [comment]
If not, can you tell me which machines are compatible with?

**Comment by daleao** [comment]
There are no issues with PFMAutomate to my knowledge. What issue are you having?

**Comment by 2970194508** [comment]
> 据我所知，PFMAutomate没有问题。你有什么问题？

When I was using PFMAutomate, some of the machines industrialized by PFM could not be given the bonus of craftsman skills, such as canning machines

**Comment by daleao** [comment]
The mod does not know which machines are for Artisans out of the box. If you have custom machines from mods other than Artisan Valley, you have to add their names to the config `ArtisanMachines`.
